QCPItemEllipse
AnchorIndex
QCPItemPosition* const QCPItemEllipse::topLeft
Referenced by anchorPixelPoint, draw, QCPItemEllipse, selectTest.
QCPItemPosition* const QCPItemEllipse::bottomRight
Referenced by anchorPixelPoint, draw, QCPItemEllipse, selectTest.
QCPItemAnchor* const QCPItemEllipse::topLeftRim
QCPItemAnchor* const QCPItemEllipse::top
QCPItemAnchor* const QCPItemEllipse::topRightRim
QCPItemAnchor* const QCPItemEllipse::right
QCPItemAnchor* const QCPItemEllipse::bottomRightRim
QCPItemAnchor* const QCPItemEllipse::bottom
QCPItemAnchor* const QCPItemEllipse::bottomLeftRim
QCPItemAnchor* const QCPItemEllipse::left
QCPItemAnchor* const QCPItemEllipse::center
Referenced by selectTest.
QPen QCPItemEllipse::mPen
Referenced by mainPen, setPen.
QPen QCPItemEllipse::mSelectedPen
Referenced by mainPen, setSelectedPen.
QBrush QCPItemEllipse::mBrush
Referenced by mainBrush, selectTest, setBrush.
QBrush QCPItemEllipse::mSelectedBrush
Referenced by mainBrush, setSelectedBrush.
QCPItemEllipse::QCPItemEllipse(QCustomPlot *parentPlot)
Creates an ellipse item and sets default values. The constructed item can be added to the plot with QCustomPlot::addItem.
References bottomRight, setBrush, QCPItemPosition::setCoords, setPen, setSelectedBrush, setSelectedPen, topLeft.
QCPItemEllipse::~QCPItemEllipse()
QPen QCPItemEllipse::pen() const
Referenced by setPen, setSelectedPen.
QPen QCPItemEllipse::selectedPen() const
QBrush QCPItemEllipse::brush() const
Referenced by setBrush, setSelectedBrush.
QBrush QCPItemEllipse::selectedBrush() const
void QCPItemEllipse::setPen(const QPen &pen)
Sets the pen that will be used to draw the line of the ellipse setSelectedPen, setBrush
References mPen, pen.
Referenced by QCPItemEllipse.
void QCPItemEllipse::setSelectedPen(const QPen &pen)
Sets the pen that will be used to draw the line of the ellipse when selected setPen, setSelected
References mSelectedPen, pen.
Referenced by QCPItemEllipse.
void QCPItemEllipse::setBrush(const QBrush &brush)
Sets the brush that will be used to fill the ellipse. To disable filling, set brush to Qt::NoBrush. setSelectedBrush, setPen
References brush, mBrush.
Referenced by QCPItemEllipse.
void QCPItemEllipse::setSelectedBrush(const QBrush &brush)
Sets the brush that will be used to fill the ellipse when selected. To disable filling, set brush to Qt::NoBrush. setBrush
References brush, mSelectedBrush.
Referenced by QCPItemEllipse.
double QCPItemEllipse::selectTest(const QPointF &pos, bool onlySelectable, QVariant *details=0) const
This function is used to decide whether a click hits a layerable object or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too. If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99). Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance). The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods. details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation. You may pass 0 as details to indicate that you are not interested in those selection details. selectEvent, deselectEvent, QCustomPlot::setInteractions
References bottomRight, center, mBrush, QCPLayerable::mParentPlot, QCPAbstractItem::mSelectable, QCPItemPosition::pixelPoint, QCustomPlot::selectionTolerance, topLeft.
void QCPItemEllipse::draw(QCPPainter *painter)
References bottomRight, QCPAbstractItem::clipRect, mainBrush, mainPen, QCPItemPosition::pixelPoint, QCPPainter::setPen, QCPLayerable::setVisible, topLeft.
QPointF QCPItemEllipse::anchorPixelPoint(int anchorId) const
References aiBottom, aiBottomLeftRim, aiBottomRightRim, aiCenter, aiLeft, aiRight, aiTop, aiTopLeftRim, aiTopRightRim, bottomRight, QCPItemPosition::pixelPoint, topLeft.
QPen QCPItemEllipse::mainPen() const
References mPen, QCPAbstractItem::mSelected, mSelectedPen.
Referenced by draw.
QBrush QCPItemEllipse::mainBrush() const
References mBrush, QCPAbstractItem::mSelected, mSelectedBrush.
Referenced by draw.