QCPGrid
bool QCPGrid::mSubGridVisible
Referenced by draw, setSubGridVisible.
bool QCPGrid::mAntialiasedSubGrid
Referenced by drawSubGridLines, setAntialiasedSubGrid.
bool QCPGrid::mAntialiasedZeroLine
Referenced by drawGridLines, setAntialiasedZeroLine.
QPen QCPGrid::mPen
Referenced by drawGridLines, setPen.
QPen QCPGrid::mSubGridPen
Referenced by drawSubGridLines, setSubGridPen.
QPen QCPGrid::mZeroLinePen
Referenced by drawGridLines, setZeroLinePen.
QCPAxis* QCPGrid::mParentAxis
Referenced by draw, drawGridLines, drawSubGridLines.
friend class QCPAxis
QCPGrid::QCPGrid(QCPAxis *parentAxis)
Creates a QCPGrid instance and sets default values. You shouldn't instantiate grids on their own, since every QCPAxis brings its own QCPGrid.
References QCPLayerable::setAntialiased, setAntialiasedSubGrid, setAntialiasedZeroLine, setPen, setSubGridPen, setSubGridVisible, setZeroLinePen.
bool QCPGrid::subGridVisible() const
bool QCPGrid::antialiasedSubGrid() const
bool QCPGrid::antialiasedZeroLine() const
QPen QCPGrid::pen() const
Referenced by setPen, setSubGridPen, setZeroLinePen.
QPen QCPGrid::subGridPen() const
QPen QCPGrid::zeroLinePen() const
void QCPGrid::setSubGridVisible(bool visible)
Sets whether grid lines at sub tick marks are drawn. setSubGridPen
References mSubGridVisible, QCPLayerable::visible.
Referenced by QCPGrid.
void QCPGrid::setAntialiasedSubGrid(bool enabled)
Sets whether sub grid lines are drawn antialiased.
References mAntialiasedSubGrid.
Referenced by QCPGrid.
void QCPGrid::setAntialiasedZeroLine(bool enabled)
Sets whether zero lines are drawn antialiased.
References mAntialiasedZeroLine.
Referenced by QCPGrid.
void QCPGrid::setPen(const QPen &pen)
Sets the pen with which (major) grid lines are drawn.
References mPen, pen.
Referenced by QCPGrid.
void QCPGrid::setSubGridPen(const QPen &pen)
Sets the pen with which sub grid lines are drawn.
References mSubGridPen, pen.
Referenced by QCPGrid.
void QCPGrid::setZeroLinePen(const QPen &pen)
Sets the pen with which zero lines are drawn. Zero lines are lines at value coordinate 0 which may be drawn with a different pen than other grid lines. To disable zero lines and just draw normal grid lines at zero, set pen to Qt::NoPen.
References mZeroLinePen, pen.
Referenced by QCPAxisRect::QCPAxisRect, QCPGrid.
void QCPGrid::applyDefaultAntialiasingHint(QCPPainter *painter) const
References QCP::aeGrid, QCPLayerable::applyAntialiasingHint, QCPLayerable::mAntialiased.
Referenced by drawGridLines.
void QCPGrid::draw(QCPPainter *painter)
References drawGridLines, drawSubGridLines, mParentAxis, mSubGridVisible.
void QCPGrid::drawGridLines(QCPPainter *painter) const
References QCP::aeZeroLine, QCPLayerable::applyAntialiasingHint, applyDefaultAntialiasingHint, QCPAxisRect::bottom, QCPAxis::coordToPixel, QCPPainter::drawLine, QCPAxisRect::left, QCPRange::lower, mAntialiasedZeroLine, QCPAxis::mAxisRect, QCPAxis::mHighestVisibleTick, QCPAxis::mLowestVisibleTick, mParentAxis, mPen, QCPAxis::mRange, QCPAxis::mTickVector, mZeroLinePen, QCPAxis::orientation, QCPAxis::range, QCPAxisRect::right, QCPPainter::setPen, QCPRange::size, QCPAxisRect::top, QCPRange::upper.
Referenced by draw.
void QCPGrid::drawSubGridLines(QCPPainter *painter) const
References QCP::aeSubGrid, QCPLayerable::applyAntialiasingHint, QCPAxisRect::bottom, QCPAxis::coordToPixel, QCPPainter::drawLine, QCPAxisRect::left, mAntialiasedSubGrid, QCPAxis::mAxisRect, mParentAxis, mSubGridPen, QCPAxis::mSubTickVector, QCPAxis::orientation, QCPAxisRect::right, QCPPainter::setPen, QCPAxisRect::top.
Referenced by draw.