QCPLayoutInset
InsetPlacement
The element may be positioned/sized arbitrarily, see setInsetRect.
QList<QCPLayoutElement*> QCPLayoutInset::mElements
Referenced by addElement, elementAt, elementCount, selectTest, takeAt, updateLayout.
QList<InsetPlacement> QCPLayoutInset::mInsetPlacement
Referenced by addElement, insetPlacement, setInsetPlacement, takeAt, updateLayout.
QList<Qt::Alignment> QCPLayoutInset::mInsetAlignment
Referenced by addElement, insetAlignment, setInsetAlignment, takeAt, updateLayout.
QList<QRectF> QCPLayoutInset::mInsetRect
Referenced by addElement, insetRect, setInsetRect, takeAt, updateLayout.
QCPLayoutInset::QCPLayoutInset()
Creates an instance of QCPLayoutInset and sets default values.
QCPLayoutInset::~QCPLayoutInset()
References QCPLayout::clear.
QCPLayoutInset::InsetPlacement QCPLayoutInset::insetPlacement(int index) const
Returns the placement type of the element with the specified index.
References elementAt, ipFree, mInsetPlacement.
Qt::Alignment QCPLayoutInset::insetAlignment(int index) const
Returns the alignment of the element with the specified index. The alignment only has a meaning, if the inset placement (setInsetPlacement) is ipBorderAligned.
References elementAt, mInsetAlignment.
QRectF QCPLayoutInset::insetRect(int index) const
Returns the rect of the element with the specified index. The rect only has a meaning, if the inset placement (setInsetPlacement) is ipFree.
References elementAt, mInsetRect.
Referenced by updateLayout.
void QCPLayoutInset::setInsetPlacement(int index, InsetPlacement placement)
Sets the inset placement type of the element with the specified index to placement. InsetPlacement
References elementAt, mInsetPlacement.
void QCPLayoutInset::setInsetAlignment(int index, Qt::Alignment alignment)
If the inset placement (setInsetPlacement) is ipBorderAligned, this function is used to set the alignment of the element with the specified index to alignment. alignment is an or combination of the following alignment flags: Qt::AlignLeft, Qt::AlignHCenter, Qt::AlighRight, Qt::AlignTop, Qt::AlignVCenter, Qt::AlignBottom. Any other alignment flags will be ignored.
References elementAt, mInsetAlignment.
void QCPLayoutInset::setInsetRect(int index, const QRectF &rect)
If the inset placement (setInsetPlacement) is ipFree, this function is used to set the position and size of the element with the specified index to rect. rect is given in fractions of the whole inset layout rect. So an inset with rect (0, 0, 1, 1) will span the entire layout. An inset with rect (0.6, 0.1, 0.35, 0.35) will be in the top right corner of the layout, with 35% width and height of the parent layout. Note that the minimum and maximum sizes of the embedded element (QCPLayoutElement::setMinimumSize, QCPLayoutElement::setMaximumSize) are enforced.
References elementAt, mInsetRect, QCPLayoutElement::rect.
void QCPLayoutInset::updateLayout()
References insetRect, ipBorderAligned, ipFree, mElements, mInsetAlignment, mInsetPlacement, mInsetRect, QCPLayoutElement::rect.
int QCPLayoutInset::elementCount() const
Returns the number of elements/cells in the layout. elements, elementAt
References mElements.
Referenced by take.
QCPLayoutElement * QCPLayoutInset::elementAt(int index) const
Returns the element in the cell with the given index. If index is invalid, returns 0. Note that even if index is valid, the respective cell may be empty in some layouts (e.g. QCPLayoutGrid), so this function may return 0 in those cases. You may use this function to check whether a cell is empty or not. elements, elementCount, takeAt
References mElements.
Referenced by insetAlignment, insetPlacement, insetRect, setInsetAlignment, setInsetPlacement, setInsetRect, take, takeAt.
QCPLayoutElement * QCPLayoutInset::takeAt(int index)
Removes the element with the given index from the layout and returns it. If the index is invalid or the cell with that index is empty, returns 0. Note that some layouts don't remove the respective cell right away but leave an empty cell after successful removal of the layout element. To collapse empty cells, use simplify. elementAt, take
References elementAt, mElements, mInsetAlignment, mInsetPlacement, mInsetRect, QCPLayout::releaseElement.
Referenced by take.
bool QCPLayoutInset::take(QCPLayoutElement *element)
Removes the specified element from the layout and returns true on success. If the element isn't in this layout, returns false. Note that some layouts don't remove the respective cell right away but leave an empty cell after successful removal of the layout element. To collapse empty cells, use simplify. takeAt
References elementAt, elementCount, takeAt.
void QCPLayoutInset::simplify()
The QCPInsetLayout does not need simplification since it can never have empty cells due to its linear index structure. This method does nothing.
double QCPLayoutInset::selectTest(const QPointF &pos, bool onlySelectable, QVariant *details=0) const
The inset layout is sensitive to events only at areas where its (visible) child elements are sensitive. If the selectTest method of any of the child elements returns a positive number for pos, this method returns a value corresponding to 0.99 times the parent plot's selection tolerance. The inset layout is not selectable itself by default. So if onlySelectable is true, -1.0 is returned. See QCPLayerable::selectTest for a general explanation of this virtual method.
References mElements, QCPLayerable::mParentPlot, QCustomPlot::selectionTolerance.
void QCPLayoutInset::addElement(QCPLayoutElement *element, Qt::Alignment alignment)
Adds the specified element to the layout as an inset aligned at the border (setInsetAlignment is initialized with ipBorderAligned). The alignment is set to alignment. alignment is an or combination of the following alignment flags: Qt::AlignLeft, Qt::AlignHCenter, Qt::AlighRight, Qt::AlignTop, Qt::AlignVCenter, Qt::AlignBottom. Any other alignment flags will be ignored. addElement(QCPLayoutElement *element, const QRectF &rect)
References QCPLayout::adoptElement, ipBorderAligned, QCPLayoutElement::layout, mElements, mInsetAlignment, mInsetPlacement, mInsetRect, QCPLayout::take.
Referenced by QCustomPlot::QCustomPlot.
void QCPLayoutInset::addElement(QCPLayoutElement *element, const QRectF &rect)
Adds the specified element to the layout as an inset with free positioning/sizing (setInsetAlignment is initialized with ipFree). The position and size is set to rect. rect is given in fractions of the whole inset layout rect. So an inset with rect (0, 0, 1, 1) will span the entire layout. An inset with rect (0.6, 0.1, 0.35, 0.35) will be in the top right corner of the layout, with 35% width and height of the parent layout. addElement(QCPLayoutElement *element, Qt::Alignment alignment)
References QCPLayout::adoptElement, ipFree, QCPLayoutElement::layout, mElements, mInsetAlignment, mInsetPlacement, mInsetRect, QCPLayoutElement::rect, QCPLayout::take.