QCPItemPosition
PositionType
Static positioning in pixels, starting from the top left corner of the viewport/widget.
PositionType QCPItemPosition::mPositionTypeX
Referenced by pixelPoint, setParentAnchorX, setPixelPoint, setTypeX.
PositionType QCPItemPosition::mPositionTypeY
Referenced by pixelPoint, setParentAnchorY, setPixelPoint, setTypeY.
QPointer<QCPAxis> QCPItemPosition::mKeyAxis
Referenced by pixelPoint, setAxes, setPixelPoint, setTypeX, setTypeY.
QPointer<QCPAxis> QCPItemPosition::mValueAxis
Referenced by pixelPoint, setAxes, setPixelPoint, setTypeX, setTypeY.
QPointer<QCPAxisRect> QCPItemPosition::mAxisRect
Referenced by axisRect, pixelPoint, setAxisRect, setPixelPoint, setTypeX, setTypeY.
double QCPItemPosition::mKey
Referenced by pixelPoint, setCoords.
double QCPItemPosition::mValue
Referenced by pixelPoint, setCoords.
QCPItemAnchor* QCPItemPosition::mParentAnchorX
Referenced by pixelPoint, setParentAnchorX, setPixelPoint, ~QCPItemPosition.
QCPItemAnchor * QCPItemPosition::mParentAnchorY
Referenced by pixelPoint, setParentAnchorY, setPixelPoint, ~QCPItemPosition.
QCPItemPosition::QCPItemPosition(QCustomPlot *parentPlot, QCPAbstractItem *parentItem, const QString name)
Creates a new QCPItemPosition. You shouldn't create QCPItemPosition instances directly, even if you want to make a new item subclass. Use QCPAbstractItem::createPosition instead, as explained in the subclassing section of the QCPAbstractItem documentation.
QCPItemPosition::~QCPItemPosition()
References QCPItemAnchor::mChildrenX, QCPItemAnchor::mChildrenY, mParentAnchorX, mParentAnchorY, parentAnchorX, parentAnchorY, QCPItemAnchor::removeChildX, QCPItemAnchor::removeChildY, setParentAnchorX, setParentAnchorY.
QCPItemPosition::PositionType * QCPItemPosition::type() const
Returns the current position type. If different types were set for X and Y (setTypeX, setTypeY), this method returns the type of the X coordinate. In that case rather use typeX() and typeY(). setType
Referenced by setType, setTypeX, setTypeY.
PositionType QCPItemPosition::typeX() const
PositionType QCPItemPosition::typeY() const
QCPItemAnchor * QCPItemPosition::parentAnchor() const
Returns the current parent anchor. If different parent anchors were set for X and Y (setParentAnchorX, setParentAnchorY), this method returns the parent anchor of the Y coordinate. In that case rather use parentAnchorX() and parentAnchorY(). setParentAnchor
Referenced by setParentAnchor, setParentAnchorX, setParentAnchorY.
QCPItemAnchor* QCPItemPosition::parentAnchorX() const
Referenced by QCPItemAnchor::~QCPItemAnchor, ~QCPItemPosition.
QCPItemAnchor* QCPItemPosition::parentAnchorY() const
Referenced by QCPItemAnchor::~QCPItemAnchor, ~QCPItemPosition.
double QCPItemPosition::key() const
Referenced by setCoords.
double QCPItemPosition::value() const
Referenced by setCoords.
QPointF QCPItemPosition::coords() const
Referenced by setParentAnchorX, setParentAnchorY.
QCPAxis* QCPItemPosition::keyAxis() const
Referenced by setAxes.
QCPAxis* QCPItemPosition::valueAxis() const
Referenced by setAxes.
QCPAxisRect * QCPItemPosition::axisRect() const
References mAxisRect.
Referenced by setAxisRect.
QPointF QCPItemPosition::pixelPoint() const
Returns the final absolute pixel position of the QCPItemPosition on the QCustomPlot surface. It includes all effects of type (setType) and possible parent anchors (setParentAnchor). setPixelPoint
References mAxisRect, mKey, mKeyAxis, mParentAnchorX, mParentAnchorY, QCPItemAnchor::mParentPlot, mPositionTypeX, mPositionTypeY, mValue, mValueAxis, QCPItemAnchor::pixelPoint, ptAbsolute, ptAxisRectRatio, ptPlotCoords, ptViewportRatio, QCustomPlot::viewport.
Referenced by QCPItemRect::anchorPixelPoint, QCPItemText::anchorPixelPoint, QCPItemEllipse::anchorPixelPoint, QCPItemBracket::anchorPixelPoint, QCPItemStraightLine::draw, QCPItemLine::draw, QCPItemCurve::draw, QCPItemRect::draw, QCPItemText::draw, QCPItemEllipse::draw, QCPItemTracer::draw, QCPItemBracket::draw, QCPItemPixmap::getFinalRect, QCPItemStraightLine::selectTest, QCPItemLine::selectTest, QCPItemCurve::selectTest, QCPItemRect::selectTest, QCPItemText::selectTest, QCPItemEllipse::selectTest, QCPItemTracer::selectTest, QCPItemBracket::selectTest, setParentAnchorX, setParentAnchorY, setPixelPoint, setTypeX, setTypeY.
void QCPItemPosition::setType(PositionType type)
Sets the type of the position. The type defines how the coordinates passed to setCoords should be handled and how the QCPItemPosition should behave in the plot. The possible values for type can be separated in two main categories: The position is regarded as a point in plot coordinates. This corresponds to ptPlotCoords and requires two axes that define the plot coordinate system. They can be specified with setAxes. By default, the QCustomPlot's x- and yAxis are used. The position is fixed on the QCustomPlot surface, i.e. independent of axis ranges. This corresponds to all other types, i.e. ptAbsolute, ptViewportRatio and ptAxisRectRatio. They differ only in the way the absolute position is described, see the documentation of PositionType for details. For ptAxisRectRatio, note that you can specify the axis rect with setAxisRect. By default this is set to the main axis rect. Note that the position type ptPlotCoords is only available (and sensible) when the position has no parent anchor (setParentAnchor). If the type is changed, the apparent pixel position on the plot is preserved. This means the coordinates as retrieved with coords() and set with setCoords may change in the process. This method sets the type for both X and Y directions. It is also possible to set different types for X and Y, see setTypeX, setTypeY.
References setTypeX, setTypeY, type.
Referenced by QCPAbstractItem::createPosition, QCPItemTracer::setGraph.
void QCPItemPosition::setTypeX(PositionType type)
This method sets the position type of the X coordinate to type. For a detailed description of what a position type is, see the documentation of setType. setType, setTypeY
References mAxisRect, mKeyAxis, mPositionTypeX, mValueAxis, pixelPoint, ptAxisRectRatio, ptPlotCoords, setPixelPoint, type.
Referenced by setParentAnchorX, setType.
void QCPItemPosition::setTypeY(PositionType type)
This method sets the position type of the Y coordinate to type. For a detailed description of what a position type is, see the documentation of setType. setType, setTypeX
References mAxisRect, mKeyAxis, mPositionTypeY, mValueAxis, pixelPoint, ptAxisRectRatio, ptPlotCoords, setPixelPoint, type.
Referenced by setParentAnchorY, setType.
bool QCPItemPosition::setParentAnchor(QCPItemAnchor *parentAnchor, bool keepPixelPosition=false)
Sets the parent of this QCPItemPosition to parentAnchor. This means the position will now follow any position changes of the anchor. The local coordinate system of positions with a parent anchor always is absolute pixels, with (0, 0) being exactly on top of the parent anchor. (Hence the type shouldn't be set to ptPlotCoords for positions with parent anchors.) if keepPixelPosition is true, the current pixel position of the QCPItemPosition is preserved during reparenting. If it's set to false, the coordinates are set to (0, 0), i.e. the position will be exactly on top of the parent anchor. To remove this QCPItemPosition from any parent anchor, set parentAnchor to 0. If the QCPItemPosition previously had no parent and the type is ptPlotCoords, the type is set to ptAbsolute, to keep the position in a valid state. This method sets the parent anchor for both X and Y directions. It is also possible to set different parents for X and Y, see setParentAnchorX, setParentAnchorY.
References parentAnchor, setParentAnchorX, setParentAnchorY.
bool QCPItemPosition::setParentAnchorX(QCPItemAnchor *parentAnchor, bool keepPixelPosition=false)
This method sets the parent anchor of the X coordinate to parentAnchor. For a detailed description of what a parent anchor is, see the documentation of setParentAnchor. setParentAnchor, setParentAnchorY
References QCPItemAnchor::addChildX, coords, mParentAnchorX, QCPItemAnchor::mParentItem, mPositionTypeX, parentAnchor, pixelPoint, ptAbsolute, ptPlotCoords, QCPItemAnchor::removeChildX, setCoords, setPixelPoint, setTypeX, QCPItemAnchor::toQCPItemPosition.
Referenced by setParentAnchor, QCPItemAnchor::~QCPItemAnchor, ~QCPItemPosition.
bool QCPItemPosition::setParentAnchorY(QCPItemAnchor *parentAnchor, bool keepPixelPosition=false)
This method sets the parent anchor of the Y coordinate to parentAnchor. For a detailed description of what a parent anchor is, see the documentation of setParentAnchor. setParentAnchor, setParentAnchorX
References QCPItemAnchor::addChildY, coords, mParentAnchorY, QCPItemAnchor::mParentItem, mPositionTypeY, parentAnchor, pixelPoint, ptAbsolute, ptPlotCoords, QCPItemAnchor::removeChildY, setCoords, setPixelPoint, setTypeY, QCPItemAnchor::toQCPItemPosition.
Referenced by setParentAnchor, QCPItemAnchor::~QCPItemAnchor, ~QCPItemPosition.
void QCPItemPosition::setCoords(double key, double value)
Sets the coordinates of this QCPItemPosition. What the coordinates mean, is defined by the type (setType, setTypeX, setTypeY). For example, if the type is ptAbsolute, key and value mean the x and y pixel position on the QCustomPlot surface. In that case the origin (0, 0) is in the top left corner of the QCustomPlot viewport. If the type is ptPlotCoords, key and value mean a point in the plot coordinate system defined by the axes set by setAxes. By default those are the QCustomPlot's xAxis and yAxis. See the documentation of setType for other available coordinate types and their meaning. If different types were configured for X and Y (setTypeX, setTypeY), key and value must also be provided in the different coordinate systems. Here, the X type refers to key, and the Y type refers to value. setPixelPoint
References key, mKey, mValue, value.
Referenced by QCPAbstractItem::createPosition, QCPItemBracket::QCPItemBracket, QCPItemCurve::QCPItemCurve, QCPItemEllipse::QCPItemEllipse, QCPItemLine::QCPItemLine, QCPItemPixmap::QCPItemPixmap, QCPItemRect::QCPItemRect, QCPItemStraightLine::QCPItemStraightLine, QCPItemText::QCPItemText, QCPItemTracer::QCPItemTracer, setCoords, setParentAnchorX, setParentAnchorY, setPixelPoint, QCPItemTracer::updatePosition.
void QCPItemPosition::setCoords(const QPointF &coords)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets the coordinates as a QPointF pos where pos.x has the meaning of key and pos.y the meaning of value of the setCoords(double key, double value) method.
References setCoords.
void QCPItemPosition::setAxes(QCPAxis *keyAxis, QCPAxis *valueAxis)
When setType is ptPlotCoords, this function may be used to specify the axes the coordinates set with setCoords relate to. By default they are set to the initial xAxis and yAxis of the QCustomPlot.
References keyAxis, mKeyAxis, mValueAxis, valueAxis.
Referenced by QCPAbstractItem::createPosition, QCPItemTracer::setGraph.
void QCPItemPosition::setAxisRect(QCPAxisRect *axisRect)
When setType is ptAxisRectRatio, this function may be used to specify the axis rect the coordinates set with setCoords relate to. By default this is set to the main axis rect of the QCustomPlot.
References axisRect, mAxisRect.
Referenced by QCPAbstractItem::createPosition.
void QCPItemPosition::setPixelPoint(const QPointF &pixelPoint)
Sets the apparent pixel position. This works no matter what type (setType) this QCPItemPosition is or what parent-child situation it is in, as coordinates are transformed appropriately, to make the position finally appear at the specified pixel values. Only if the type is ptAbsolute and no parent anchor is set, this function's effect is identical to that of setCoords. pixelPoint, setCoords
References mAxisRect, mKeyAxis, mParentAnchorX, mParentAnchorY, QCPItemAnchor::mParentPlot, mPositionTypeX, mPositionTypeY, mValueAxis, QCPItemAnchor::pixelPoint, pixelPoint, ptAbsolute, ptAxisRectRatio, ptPlotCoords, ptViewportRatio, setCoords, QCustomPlot::viewport.
Referenced by setParentAnchorX, setParentAnchorY, setTypeX, setTypeY.
virtual QCPItemPosition* QCPItemPosition::toQCPItemPosition()
Returns 0 if this instance is merely a QCPItemAnchor, and a valid pointer of type QCPItemPosition* if it actually is a QCPItemPosition (which is a subclass of QCPItemAnchor). This safe downcast functionality could also be achieved with a dynamic_cast. However, QCustomPlot avoids dynamic_cast to work with projects that don't have RTTI support enabled (e.g. -fno-rtti flag with gcc compiler).