QCPRange
double QCPRange::lower
Referenced by QCPColorMapData::cellToCoord, center, QCPColorGradient::color, QCPColorGradient::colorize, contains, QCPColorMapData::coordToCell, QCPAxis::coordToPixel, QCPColorMapData::data, QCPColorMap::draw, QCPGrid::drawGridLines, expand, QCPAxis::generateAutoTicks, QCPCurve::getCurveData, QCPGraph::getKeyRange, QCPCurve::getKeyRange, QCPBars::getKeyRange, QCPColorMap::getKeyRange, QCPFinancial::getKeyRange, QCPGraph::getPreparedData, QCPGraph::getValueRange, QCPCurve::getValueRange, QCPBars::getValueRange, QCPColorMap::getValueRange, QCPFinancial::getValueRange, QCPAxisRect::mouseMoveEvent, QCPAxis::moveRange, normalize, operator==, QCPAxis::pixelToCoord, QCPColorMapData::recalculateDataBounds, QCPAxis::rescale, QCPColorScale::rescaleDataRange, QCPGraph::rescaleKeyAxis, QCPAbstractPlottable::rescaleKeyAxis, QCPGraph::rescaleValueAxis, QCPAbstractPlottable::rescaleValueAxis, sanitizedForLinScale, sanitizedForLogScale, QCPAxis::scaleRange, QCPColorMapData::setCell, QCPColorMapData::setData, QCPColorScale::setDataRange, QCPColorMap::setDataRange, QCPAxis::setRange, QCPAxis::setRangeLower, QCPAxis::setupTickVectors, size, validRange, QCPAxis::visibleTickBounds.
double QCPRange::upper
Referenced by QCPColorMapData::cellToCoord, center, QCPColorGradient::color, QCPColorGradient::colorize, contains, QCPColorMapData::coordToCell, QCPAxis::coordToPixel, QCPColorMapData::data, QCPColorMap::draw, QCPGrid::drawGridLines, expand, QCPAxis::generateAutoTicks, QCPCurve::getCurveData, QCPGraph::getKeyRange, QCPCurve::getKeyRange, QCPBars::getKeyRange, QCPColorMap::getKeyRange, QCPFinancial::getKeyRange, QCPGraph::getPreparedData, QCPGraph::getValueRange, QCPCurve::getValueRange, QCPBars::getValueRange, QCPColorMap::getValueRange, QCPFinancial::getValueRange, QCPGraph::lowerFillBasePoint, QCPAxisRect::mouseMoveEvent, QCPAxis::moveRange, normalize, operator==, QCPAxis::pixelToCoord, QCPColorMapData::recalculateDataBounds, QCPAxis::rescale, QCPColorScale::rescaleDataRange, QCPGraph::rescaleKeyAxis, QCPAbstractPlottable::rescaleKeyAxis, QCPGraph::rescaleValueAxis, QCPAbstractPlottable::rescaleValueAxis, sanitizedForLinScale, sanitizedForLogScale, QCPAxis::scaleRange, QCPColorMapData::setCell, QCPColorMapData::setData, QCPColorScale::setDataRange, QCPColorMap::setDataRange, QCPAxis::setRange, QCPAxis::setRangeUpper, QCPAxis::setupTickVectors, size, QCPGraph::upperFillBasePoint, validRange, QCPAxis::visibleTickBounds.
const double QCPRange::minRange
Minimum range size (upper - lower) the range changing functions will accept. Smaller intervals would cause errors due to the 11-bit exponent of double precision numbers, corresponding to a minimum magnitude of roughly 1e-308. validRange, maxRange
Referenced by validRange.
const double QCPRange::maxRange
Maximum values (negative and positive) the range will accept in range-changing functions. Larger absolute values would cause errors due to the 11-bit exponent of double precision numbers, corresponding to a maximum magnitude of roughly 1e308. Since the number of planck-volumes in the entire visible universe is only ~1e183, this should be enough. validRange, minRange
Referenced by validRange.
QCPRange::QCPRange()
Constructs a range with lower and upper set to zero.
QCPRange::QCPRange(double lower, double upper)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Constructs a range with the specified lower and upper values.
References normalize.
bool QCPRange::operator==(const QCPRange &other) const
References lower, upper.
bool QCPRange::operator!=(const QCPRange &other) const
QCPRange & QCPRange::operator+=(const double &value)
Adds value to both boundaries of the range.
QCPRange & QCPRange::operator-=(const double &value)
Subtracts value from both boundaries of the range.
QCPRange & QCPRange::operator*=(const double &value)
Multiplies both boundaries of the range by value.
QCPRange & QCPRange::operator/=(const double &value)
Divides both boundaries of the range by value.
double QCPRange::size() const
Returns the size of the range, i.e. upper-lower
References lower, upper.
Referenced by QCPColorGradient::color, QCPColorGradient::colorize, QCPAxis::coordToPixel, QCPGrid::drawGridLines, QCPAxis::generateAutoTicks, QCPAxis::pixelToCoord, QCPAxis::rescale, QCPColorScale::rescaleDataRange, QCPAbstractPlottable::rescaleKeyAxis, QCPAbstractPlottable::rescaleValueAxis, QCPAxis::setScaleRatio, QCPAxis::setupTickVectors.
double QCPRange::center() const
Returns the center of the range, i.e. (upper+lower)*0.5
References lower, upper.
void QCPRange::normalize()
Makes sure lower is numerically smaller than upper. If this is not the case, the values are swapped.
References lower, upper.
Referenced by QCPColorMap::getKeyRange, QCPColorMap::getValueRange, QCPRange, sanitizedForLinScale, sanitizedForLogScale.
void QCPRange::expand(const QCPRange &otherRange)
Expands this range such that otherRange is contained in the new range. It is assumed that both this range and otherRange are normalized (see normalize). If otherRange is already inside the current range, this function does nothing. expanded
References lower, upper.
Referenced by expanded, QCPAxis::rescale, QCPColorScale::rescaleDataRange, QCPAbstractPlottable::rescaleKeyAxis, QCPAbstractPlottable::rescaleValueAxis.
QCPRange QCPRange::expanded(const QCPRange &otherRange) const
Returns an expanded range that contains this and otherRange. It is assumed that both this range and otherRange are normalized (see normalize). expand
References expand.
QCPRange QCPRange::sanitizedForLogScale() const
Returns a sanitized version of the range. Sanitized means for logarithmic scales, that the range won't span the positive and negative sign domain, i.e. contain zero. Further lower will always be numerically smaller (or equal) to upper. If the original range does span positive and negative sign domains or contains zero, the returned range will try to approximate the original range as good as possible. If the positive interval of the original range is wider than the negative interval, the returned range will only contain the positive interval, with lower bound set to rangeFac or rangeFac *upper, whichever is closer to zero. Same procedure is used if the negative interval is wider than the positive interval, this time by changing the upper bound.
References lower, normalize, upper.
Referenced by QCPAxis::scaleRange, QCPColorMap::setDataRange, QCPColorScale::setDataScaleType, QCPColorMap::setDataScaleType, QCPAxis::setRange, QCPAxis::setRangeLower, QCPAxis::setRangeUpper, QCPAxis::setScaleType.
QCPRange QCPRange::sanitizedForLinScale() const
Returns a sanitized version of the range. Sanitized means for linear scales, that lower will always be numerically smaller (or equal) to upper.
References lower, normalize, upper.
Referenced by QCPAxis::scaleRange, QCPColorMap::setDataRange, QCPAxis::setRange, QCPAxis::setRangeLower, QCPAxis::setRangeUpper.
bool QCPRange::contains(double value) const
Returns true when value lies within or exactly on the borders of the range.
References lower, upper.
Referenced by QCPFinancial::candlestickSelectTest, QCPStatisticalBox::selectTest, QCPColorMap::selectTest.
const QCPRange operator+(const QCPRange &, double)
Adds value to both boundaries of the range.
const QCPRange operator+(double, const QCPRange &)
Adds value to both boundaries of the range.
const QCPRange operator-(const QCPRange &range, double value)
Subtracts value from both boundaries of the range.
const QCPRange operator*(const QCPRange &range, double value)
Multiplies both boundaries of the range by value.
const QCPRange operator*(double value, const QCPRange &range)
Multiplies both boundaries of the range by value.
const QCPRange operator/(const QCPRange &range, double value)
Divides both boundaries of the range by value.
bool QCPRange::validRange(double lower, double upper)
Checks, whether the specified range is within valid bounds, which are defined as QCPRange::maxRange and QCPRange::minRange. A valid range means: range bounds within -maxRange and maxRange range size above minRange range size below maxRange
References lower, maxRange, minRange, upper.
Referenced by QCPAxis::rescale, QCPColorScale::rescaleDataRange, QCPAbstractPlottable::rescaleKeyAxis, QCPAbstractPlottable::rescaleValueAxis, QCPAxis::scaleRange, QCPColorMap::setDataRange, QCPAxis::setRange.
bool QCPRange::validRange(const QCPRange &range)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Checks, whether the specified range is within valid bounds, which are defined as QCPRange::maxRange and QCPRange::minRange. A valid range means: range bounds within -maxRange and maxRange range size above minRange range size below maxRange
References lower, maxRange, minRange, upper.