QCPAbstractLegendItem
QCPLegend* QCPAbstractLegendItem::mParentLegend
Referenced by deselectEvent, QCPPlottableLegendItem::draw, QCPPlottableLegendItem::getIconBorderPen, QCPPlottableLegendItem::minimumSizeHint, selectEvent, selectTest.
QFont QCPAbstractLegendItem::mFont
Referenced by QCPPlottableLegendItem::getFont, setFont.
QColor QCPAbstractLegendItem::mTextColor
Referenced by QCPPlottableLegendItem::getTextColor, setTextColor.
QFont QCPAbstractLegendItem::mSelectedFont
Referenced by QCPPlottableLegendItem::getFont, setSelectedFont.
QColor QCPAbstractLegendItem::mSelectedTextColor
Referenced by QCPPlottableLegendItem::getTextColor, setSelectedTextColor.
bool QCPAbstractLegendItem::mSelectable
Referenced by deselectEvent, selectEvent, selectTest, setSelectable.
bool QCPAbstractLegendItem::mSelected
Referenced by deselectEvent, QCPPlottableLegendItem::getFont, QCPPlottableLegendItem::getIconBorderPen, QCPPlottableLegendItem::getTextColor, selectEvent, setSelected.
friend class QCPLegend
QCPAbstractLegendItem::QCPAbstractLegendItem(QCPLegend *parent)
Constructs a QCPAbstractLegendItem and associates it with the QCPLegend parent. This does not cause the item to be added to parent, so QCPLegend::addItem must be called separately.
References QCPLayerable::setLayer, QCPLayoutElement::setMargins.
QCPLegend* QCPAbstractLegendItem::parentLegend() const
QFont QCPAbstractLegendItem::font() const
Referenced by setFont, setSelectedFont.
QColor QCPAbstractLegendItem::textColor() const
QFont QCPAbstractLegendItem::selectedFont() const
QColor QCPAbstractLegendItem::selectedTextColor() const
bool QCPAbstractLegendItem::selectable() const
Referenced by setSelectable.
bool QCPAbstractLegendItem::selected() const
Referenced by QCPLegend::selectedParts, setSelected.
void QCPAbstractLegendItem::setFont(const QFont &font)
Sets the default font of this specific legend item to font. setTextColor, QCPLegend::setFont
References font, mFont.
Referenced by QCPLegend::setFont.
void QCPAbstractLegendItem::setTextColor(const QColor &color)
Sets the default text color of this specific legend item to color. setFont, QCPLegend::setTextColor
References mTextColor.
Referenced by QCPLegend::setTextColor.
void QCPAbstractLegendItem::setSelectedFont(const QFont &font)
When this legend item is selected, font is used to draw generic text, instead of the normal font set with setFont. setFont, QCPLegend::setSelectedFont
References font, mSelectedFont.
Referenced by QCPLegend::setSelectedFont.
void QCPAbstractLegendItem::setSelectedTextColor(const QColor &color)
When this legend item is selected, color is used to draw generic text, instead of the normal color set with setTextColor. setTextColor, QCPLegend::setSelectedTextColor
References mSelectedTextColor.
Referenced by QCPLegend::setSelectedTextColor.
void QCPAbstractLegendItem::setSelectable(bool selectable)
Sets whether this specific legend item is selectable. setSelectedParts, QCustomPlot::setInteractions
References mSelectable, selectable, selectableChanged.
void QCPAbstractLegendItem::setSelected(bool selected)
Sets whether this specific legend item is selected. It is possible to set the selection state of this item by calling this function directly, even if setSelectable is set to false. setSelectableParts, QCustomPlot::setInteractions
References mSelected, selected, selectionChanged.
Referenced by deselectEvent, selectEvent, QCPLegend::setSelectedParts.
double QCPAbstractLegendItem::selectTest(const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Layout elements are sensitive to events inside their outer rect. If pos is within the outer rect, this method returns a value corresponding to 0.99 times the parent plot's selection tolerance. However, layout elements are not selectable by default. So if onlySelectable is true, -1.0 is returned. See QCPLayerable::selectTest for a general explanation of this virtual method. QCPLayoutElement subclasses may reimplement this method to provide more specific selection test behaviour.
References mParentLegend, QCPLayerable::mParentPlot, QCPLayoutElement::mRect, mSelectable, QCPLegend::selectableParts, QCustomPlot::selectionTolerance, QCPLegend::spItems.
void QCPAbstractLegendItem::selectionChanged(bool selected)
This signal is emitted when the selection state of this legend item has changed, either by user interaction or by a direct call to setSelected.
Referenced by setSelected.
void QCPAbstractLegendItem::selectableChanged(bool selectable)
Referenced by setSelectable.
QCP::Interaction QCPAbstractLegendItem::selectionCategory() const
References QCP::iSelectLegend.
void QCPAbstractLegendItem::applyDefaultAntialiasingHint(QCPPainter *painter) const
References QCP::aeLegendItems, QCPLayerable::applyAntialiasingHint, QCPLayerable::mAntialiased.
QRect QCPAbstractLegendItem::clipRect() const
References QCPLayoutElement::mOuterRect.
virtual void QCPAbstractLegendItem::draw(QCPPainter *painter)=0
void QCPAbstractLegendItem::selectEvent(QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
References mParentLegend, mSelectable, mSelected, QCPLegend::selectableParts, setSelected, QCPLegend::spItems.
void QCPAbstractLegendItem::deselectEvent(bool *selectionStateChanged)
References mParentLegend, mSelectable, mSelected, QCPLegend::selectableParts, setSelected, QCPLegend::spItems.