QCPColorScaleAxisRectPrivate
QCPColorScale* QCPColorScaleAxisRectPrivate::mParentColorScale
Referenced by draw, updateGradientImage.
QImage QCPColorScaleAxisRectPrivate::mGradientImage
Referenced by draw, updateGradientImage.
bool QCPColorScaleAxisRectPrivate::mGradientImageInvalidated
Referenced by draw, updateGradientImage.
friend class QCPColorScale
QCPColorScaleAxisRectPrivate::QCPColorScaleAxisRectPrivate(QCPColorScale *parentColorScale)
Creates a new instance, as a child of parentColorScale.
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxisRect::axis, axisSelectableChanged, axisSelectionChanged, QCPAxis::grid, QCPLayerable::layerChanged, QCPLayerable::setLayer, QCPLayoutElement::setMinimumMargins, QCPAxis::setPadding, QCPLayerable::setParentLayerable, QCPLayerable::setVisible.
void QCPColorScaleAxisRectPrivate::draw(QCPPainter *painter)
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxisRect::draw, QCPColorScale::mColorAxis, mGradientImage, mGradientImageInvalidated, mParentColorScale, QCPLayoutElement::rect, QCPColorScale::type, updateGradientImage.
void QCPColorScaleAxisRectPrivate::updateGradientImage()
References QCPAxis::atBottom, QCPAxis::atTop, QCPColorGradient::color, QCPColorGradient::colorize, QCPColorGradient::levelCount, QCPColorScale::mGradient, mGradientImage, mGradientImageInvalidated, mParentColorScale, QCPColorScale::mType, QCPLayoutElement::rect.
Referenced by draw.
void QCPColorScaleAxisRectPrivate::axisSelectionChanged(QCPAxis::SelectableParts selectedParts)
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxisRect::axis, QCPAxis::setSelectedParts, QCPAxis::spAxis.
Referenced by QCPColorScaleAxisRectPrivate.
void QCPColorScaleAxisRectPrivate::axisSelectableChanged(QCPAxis::SelectableParts selectableParts)
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxisRect::axis, QCPAxis::setSelectableParts, QCPAxis::spAxis.
Referenced by QCPColorScaleAxisRectPrivate.
int QCPAxisRect::calculateAutoMargin(QCP::MarginSide side)
void QCPAxisRect::mousePressEvent(QMouseEvent *event)
void QCPAxisRect::mouseMoveEvent(QMouseEvent *event)
void QCPAxisRect::mouseReleaseEvent(QMouseEvent *event)
void QCPAxisRect::wheelEvent(QWheelEvent *event)
void QCPAxisRect::update(UpdatePhase phase)
This method is called automatically upon replot and doesn't need to be called by users of QCPAxisRect. Calls the base class implementation to update the margins (see QCPLayoutElement::update), and finally passes the rect to the inset layout (insetLayout) and calls its QCPInsetLayout::update function.