QCPPlottableLegendItem
QCPAbstractPlottable* QCPPlottableLegendItem::mPlottable
Referenced by draw, minimumSizeHint.
QCPPlottableLegendItem::QCPPlottableLegendItem(QCPLegend *parent, QCPAbstractPlottable *plottable)
Creates a new legend item associated with plottable. Once it's created, it can be added to the legend via QCPLegend::addItem. A more convenient way of adding/removing a plottable to/from the legend is via the functions QCPAbstractPlottable::addToLegend and QCPAbstractPlottable::removeFromLegend.
QCPAbstractPlottable* QCPPlottableLegendItem::plottable()
void QCPPlottableLegendItem::draw(QCPPainter *painter)
References QCPAbstractPlottable::drawLegendIcon, getFont, getIconBorderPen, getTextColor, QCPLegend::iconSize, QCPLegend::iconTextPadding, QCPAbstractLegendItem::mParentLegend, mPlottable, QCPLayoutElement::mRect, QCPAbstractPlottable::name, QCPPainter::restore, QCPPainter::save, QCPPainter::setPen.
QSize QCPPlottableLegendItem::minimumSizeHint() const
Returns the minimum size this layout element (the inner rect) may be compressed to. if a minimum size (setMinimumSize) was not set manually, parent layouts consult this function to determine the minimum allowed size of this layout element. (A manual minimum size is considered set if it is non-zero.)
References getFont, QCPLegend::iconSize, QCPLegend::iconTextPadding, QCPLayoutElement::mMargins, QCPAbstractLegendItem::mParentLegend, mPlottable, QCPAbstractPlottable::name.
QPen QCPPlottableLegendItem::getIconBorderPen() const
References QCPLegend::iconBorderPen, QCPAbstractLegendItem::mParentLegend, QCPAbstractLegendItem::mSelected, QCPLegend::selectedIconBorderPen.
Referenced by draw.
QColor QCPPlottableLegendItem::getTextColor() const
References QCPAbstractLegendItem::mSelected, QCPAbstractLegendItem::mSelectedTextColor, QCPAbstractLegendItem::mTextColor.
Referenced by draw.
QFont QCPPlottableLegendItem::getFont() const
References QCPAbstractLegendItem::mFont, QCPAbstractLegendItem::mSelected, QCPAbstractLegendItem::mSelectedFont.
Referenced by draw, minimumSizeHint.