QCPGraph
LineStyle
data points are not connected with any lines (e.g. data only represented with symbols according to the scatter style, see setScatterStyle)
ErrorType
No error bars are shown.
QCPDataMap* QCPGraph::mData
Referenced by addData, clearData, countDataInBounds, draw, getKeyRange, getPreparedData, getValueRange, getVisibleDataBounds, pointDistance, QCPGraph, removeData, removeDataAfter, removeDataBefore, rescaleKeyAxis, rescaleValueAxis, selectTest, setData, setDataBothError, setDataKeyError, setDataValueError, ~QCPGraph.
QPen QCPGraph::mErrorPen
Referenced by drawScatterPlot, setErrorPen.
LineStyle QCPGraph::mLineStyle
Referenced by draw, drawFill, drawLegendIcon, getPlotData, pointDistance, setLineStyle.
QCPScatterStyle QCPGraph::mScatterStyle
Referenced by draw, drawError, drawLegendIcon, drawScatterPlot, pointDistance, setScatterStyle.
ErrorType QCPGraph::mErrorType
Referenced by drawError, drawScatterPlot, setErrorType.
double QCPGraph::mErrorBarSize
Referenced by drawError, setErrorBarSize.
bool QCPGraph::mErrorBarSkipSymbol
Referenced by drawError, setErrorBarSkipSymbol.
QPointer<QCPGraph> QCPGraph::mChannelFillGraph
Referenced by drawFill, getChannelFillPolygon, setChannelFillGraph.
bool QCPGraph::mAdaptiveSampling
Referenced by getPreparedData, setAdaptiveSampling.
friend class QCustomPlot
friend class QCPLegend
QCPGraph::QCPGraph(QCPAxis *keyAxis, QCPAxis *valueAxis)
Constructs a graph which uses keyAxis as its key axis ("x") and valueAxis as its value axis ("y"). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though. The constructed QCPGraph can be added to the plot with QCustomPlot::addPlottable, QCustomPlot then takes ownership of the graph. To directly create a graph inside a plot, you can also use the simpler QCustomPlot::addGraph function.
References etNone, lsLine, mData, setAdaptiveSampling, QCPAbstractPlottable::setBrush, setChannelFillGraph, setErrorBarSize, setErrorBarSkipSymbol, setErrorPen, setErrorType, setLineStyle, QCPAbstractPlottable::setPen, QCPAbstractPlottable::setSelectedBrush, QCPAbstractPlottable::setSelectedPen.
QCPGraph::~QCPGraph()
References mData.
QCPDataMap * QCPGraph::data() const
Returns a pointer to the internal data storage of type QCPDataMap. You may use it to directly manipulate the data, which may be more convenient and faster than using the regular setData or addData methods, in certain situations.
Referenced by addData, channelFillGraph, drawError, findIndexAboveX, findIndexAboveY, findIndexBelowX, findIndexBelowY, Simulator::PlotMouse, setData, QCPItemTracer::updatePosition.
LineStyle QCPGraph::lineStyle() const
QCPScatterStyle QCPGraph::scatterStyle() const
ErrorType QCPGraph::errorType() const
Referenced by setErrorType.
QPen QCPGraph::errorPen() const
double QCPGraph::errorBarSize() const
bool QCPGraph::errorBarSkipSymbol() const
QCPGraph* QCPGraph::channelFillGraph() const
References data.
bool QCPGraph::adaptiveSampling() const
void QCPGraph::setData(QCPDataMap *data, bool copy=false)
Replaces the current data with the provided data. If copy is set to true, data points in data will only be copied. if false, the graph takes ownership of the passed data and replaces the internal data pointer with it. This is significantly faster than copying for large datasets. Alternatively, you can also access and modify the graph's data via the data method, which returns a pointer to the internal QCPDataMap.
References data, mData.
Referenced by Simulator::PlotMouse.
void QCPGraph::setData(const QVector< double > &key, const QVector< double > &value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Replaces the current data with the provided points in key and value pairs. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
References QCPData::key, mData, QCPData::value.
void QCPGraph::setDataKeyError(const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyError)
Replaces the current data with the provided points in key and value pairs. Additionally the symmetrical key error of the data points are set to the values in keyError. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector. For asymmetrical errors (plus different from minus), see the overloaded version of this function.
References QCPData::key, QCPData::keyErrorMinus, QCPData::keyErrorPlus, mData, QCPData::value.
void QCPGraph::setDataKeyError(const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyErrorMinus, const QVector< double > &keyErrorPlus)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Replaces the current data with the provided points in key and value pairs. Additionally the negative key error of the data points are set to the values in keyErrorMinus, the positive key error to keyErrorPlus. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
References QCPData::key, QCPData::keyErrorMinus, QCPData::keyErrorPlus, mData, QCPData::value.
void QCPGraph::setDataValueError(const QVector< double > &key, const QVector< double > &value, const QVector< double > &valueError)
Replaces the current data with the provided points in key and value pairs. Additionally the symmetrical value error of the data points are set to the values in valueError. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector. For asymmetrical errors (plus different from minus), see the overloaded version of this function.
References QCPData::key, mData, QCPData::value, QCPData::valueErrorMinus, QCPData::valueErrorPlus.
void QCPGraph::setDataValueError(const QVector< double > &key, const QVector< double > &value, const QVector< double > &valueErrorMinus, const QVector< double > &valueErrorPlus)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Replaces the current data with the provided points in key and value pairs. Additionally the negative value error of the data points are set to the values in valueErrorMinus, the positive value error to valueErrorPlus. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
References QCPData::key, mData, QCPData::value, QCPData::valueErrorMinus, QCPData::valueErrorPlus.
void QCPGraph::setDataBothError(const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyError, const QVector< double > &valueError)
Replaces the current data with the provided points in key and value pairs. Additionally the symmetrical key and value errors of the data points are set to the values in keyError and valueError. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector. For asymmetrical errors (plus different from minus), see the overloaded version of this function.
References QCPData::key, QCPData::keyErrorMinus, QCPData::keyErrorPlus, mData, QCPData::value, QCPData::valueErrorMinus, QCPData::valueErrorPlus.
void QCPGraph::setDataBothError(const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyErrorMinus, const QVector< double > &keyErrorPlus, const QVector< double > &valueErrorMinus, const QVector< double > &valueErrorPlus)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Replaces the current data with the provided points in key and value pairs. Additionally the negative key and value errors of the data points are set to the values in keyErrorMinus and valueErrorMinus. The positive key and value errors are set to the values in keyErrorPlus valueErrorPlus. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
References QCPData::key, QCPData::keyErrorMinus, QCPData::keyErrorPlus, mData, QCPData::value, QCPData::valueErrorMinus, QCPData::valueErrorPlus.
void QCPGraph::setLineStyle(LineStyle ls)
Sets how the single data points are connected in the plot. For scatter-only plots, set ls to lsNone and setScatterStyle to the desired scatter style. setScatterStyle
References mLineStyle.
Referenced by QCPGraph.
void QCPGraph::setScatterStyle(const QCPScatterStyle &style)
Sets the visual appearance of single data points in the plot. If set to QCPScatterStyle::ssNone, no scatter points are drawn (e.g. for line-only-plots with appropriate line style). QCPScatterStyle, setLineStyle
References mScatterStyle.
void QCPGraph::setErrorType(ErrorType errorType)
Sets which kind of error bars (Key Error, Value Error or both) should be drawn on each data point. If you set errorType to something other than etNone, make sure to actually pass error data via the specific setData functions along with the data points (e.g. setDataValueError, setDataKeyError, setDataBothError). ErrorType
References errorType, mErrorType.
Referenced by QCPGraph.
void QCPGraph::setErrorPen(const QPen &pen)
Sets the pen with which the error bars will be drawn. setErrorBarSize, setErrorType
References mErrorPen, QCPAbstractPlottable::pen.
Referenced by QCPGraph.
void QCPGraph::setErrorBarSize(double size)
Sets the width of the handles at both ends of an error bar in pixels.
References mErrorBarSize.
Referenced by QCPGraph.
void QCPGraph::setErrorBarSkipSymbol(bool enabled)
If enabled is set to true, the error bar will not be drawn as a solid line under the scatter symbol but leave some free space around the symbol. This feature uses the current scatter size (QCPScatterStyle::setSize) to determine the size of the area to leave blank. So when drawing Pixmaps as scatter points (QCPScatterStyle::ssPixmap), the scatter size must be set manually to a value corresponding to the size of the Pixmap, if the error bars should leave gaps to its boundaries. setErrorType, setErrorBarSize, setScatterStyle
References mErrorBarSkipSymbol.
Referenced by QCPGraph.
void QCPGraph::setChannelFillGraph(QCPGraph *targetGraph)
Sets the target graph for filling the area between this graph and targetGraph with the current brush (setBrush). When targetGraph is set to 0, a normal graph fill to the zero-value-line will be shown. To disable any filling, set the brush to Qt::NoBrush. setBrush
References mChannelFillGraph, QCPLayerable::mParentPlot.
Referenced by QCPGraph.
void QCPGraph::setAdaptiveSampling(bool enabled)
Sets whether adaptive sampling shall be used when plotting this graph. QCustomPlot's adaptive sampling technique can drastically improve the replot performance for graphs with a larger number of points (e.g. above 10,000), without notably changing the appearance of the graph. By default, adaptive sampling is enabled. Even if enabled, QCustomPlot decides whether adaptive sampling shall actually be used on a per-graph basis. So leaving adaptive sampling enabled has no disadvantage in almost all cases. A line plot of 500,000 points without and with adaptive sampling As can be seen, line plots experience no visual degradation from adaptive sampling. Outliers are reproduced reliably, as well as the overall shape of the data set. The replot time reduces dramatically though. This allows QCustomPlot to display large amounts of data in realtime. A scatter plot of 100,000 points without and with adaptive sampling Care must be taken when using high-density scatter plots in combination with adaptive sampling. The adaptive sampling algorithm treats scatter plots more carefully than line plots which still gives a significant reduction of replot times, but not quite as much as for line plots. This is because scatter plots inherently need more data points to be preserved in order to still resemble the original, non-adaptive-sampling plot. As shown above, the results still aren't quite identical, as banding occurs for the outer data points. This is in fact intentional, such that the boundaries of the data cloud stay visible to the viewer. How strong the banding appears, depends on the point density, i.e. the number of points in the plot. For some situations with scatter plots it might thus be desirable to manually turn adaptive sampling off. For example, when saving the plot to disk. This can be achieved by setting enabled to false before issuing a command like QCustomPlot::savePng, and setting enabled back to true afterwards.
References mAdaptiveSampling.
Referenced by QCPGraph.
void QCPGraph::addData(const QCPDataMap &dataMap)
Adds the provided data points in dataMap to the current data. Alternatively, you can also access and modify the graph's data via the data method, which returns a pointer to the internal QCPDataMap. removeData
References mData.
void QCPGraph::addData(const QCPData &data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point in data to the current data. Alternatively, you can also access and modify the graph's data via the data method, which returns a pointer to the internal QCPDataMap. removeData
References data, mData.
void QCPGraph::addData(double key, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point as key and value pair to the current data. Alternatively, you can also access and modify the graph's data via the data method, which returns a pointer to the internal QCPDataMap. removeData
References QCPData::key, mData, QCPData::value.
void QCPGraph::addData(const QVector< double > &keys, const QVector< double > &values)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data points as key and value pairs to the current data. Alternatively, you can also access and modify the graph's data via the data method, which returns a pointer to the internal QCPDataMap. removeData
References QCPData::key, mData, QCPData::value.
void QCPGraph::removeDataBefore(double key)
Removes all data points with keys smaller than key. addData, clearData
References mData.
void QCPGraph::removeDataAfter(double key)
Removes all data points with keys greater than key. addData, clearData
References mData.
void QCPGraph::removeData(double fromKey, double toKey)
Removes all data points with keys between fromKey and toKey. if fromKey is greater or equal to toKey, the function does nothing. To remove a single data point with known key, use removeData(double key). addData, clearData
References mData.
void QCPGraph::removeData(double key)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Removes a single data point at key. If the position is not known with absolute precision, consider using removeData(double fromKey, double toKey) with a small fuzziness interval around the suspected position, depeding on the precision with which the key is known. addData, clearData
References mData.
void QCPGraph::clearData()
Removes all data points. removeData, removeDataAfter, removeDataBefore
References mData.
double QCPGraph::selectTest(const QPointF &pos, bool onlySelectable, QVariant *details=0) const
This function is used to decide whether a click hits a layerable object or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too. If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99). Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance). The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods. details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation. You may pass 0 as details to indicate that you are not interested in those selection details. selectEvent, deselectEvent, QCustomPlot::setInteractions
References mData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mSelectable, QCPAbstractPlottable::mValueAxis, pointDistance.
void QCPGraph::rescaleAxes(bool onlyEnlarge, bool includeErrorBars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Allows to define whether error bars are taken into consideration when determining the new axis range. rescaleKeyAxis, rescaleValueAxis, QCPAbstractPlottable::rescaleAxes, QCustomPlot::rescaleAxes
References rescaleKeyAxis, rescaleValueAxis.
void QCPGraph::rescaleKeyAxis(bool onlyEnlarge, bool includeErrorBars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Allows to define whether error bars (of kind QCPGraph::etKey) are taken into consideration when determining the new axis range. rescaleAxes, QCPAbstractPlottable::rescaleKeyAxis
References getKeyRange, QCPAbstractPlottable::keyAxis, QCPRange::lower, mData, QCPAbstractPlottable::mKeyAxis, QCPAxis::range, QCPAxis::scaleType, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, QCPAxis::setRange, QCPAxis::stLogarithmic, QCPRange::upper.
void QCPGraph::rescaleValueAxis(bool onlyEnlarge, bool includeErrorBars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Allows to define whether error bars (of kind QCPGraph::etValue) are taken into consideration when determining the new axis range. rescaleAxes, QCPAbstractPlottable::rescaleValueAxis
References getValueRange, QCPRange::lower, mData, QCPAbstractPlottable::mValueAxis, QCPAxis::range, QCPAxis::scaleType, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, QCPAxis::setRange, QCPAxis::stLogarithmic, QCPRange::upper, QCPAbstractPlottable::valueAxis.
void QCPAbstractPlottable::rescaleAxes(bool onlyEnlarge=false) const
Rescales the key and value axes associated with this plottable to contain all displayed data, so the whole plottable is visible. If the scaling of an axis is logarithmic, rescaleAxes will make sure not to rescale to an illegal range i.e. a range containing different signs and/or zero. Instead it will stay in the current sign domain and ignore all parts of the plottable that lie outside of that domain. onlyEnlarge makes sure the ranges are only expanded, never reduced. So it's possible to show multiple plottables in their entirety by multiple calls to rescaleAxes where the first call has onlyEnlarge set to false (the default), and all subsequent set to true. rescaleKeyAxis, rescaleValueAxis, QCustomPlot::rescaleAxes, QCPAxis::rescale
void QCPAbstractPlottable::rescaleKeyAxis(bool onlyEnlarge=false) const
Rescales the key axis of the plottable so the whole plottable is visible. See rescaleAxes for detailed behaviour.
Referenced by rescaleAxes.
void QCPAbstractPlottable::rescaleValueAxis(bool onlyEnlarge=false) const
Rescales the value axis of the plottable so the whole plottable is visible. Returns true if the axis was actually scaled. This might not be the case if this plottable has an invalid range, e.g. because it has no data points. See rescaleAxes for detailed behaviour.
Referenced by rescaleAxes.
void QCPGraph::draw(QCPPainter *painter)
References drawFill, drawImpulsePlot, drawLinePlot, drawScatterPlot, getPlotData, QCP::isInvalidData, QCPScatterStyle::isNone, lsImpulse, lsNone, mData, QCPAbstractPlottable::mKeyAxis, mLineStyle, mScatterStyle, QCPAbstractPlottable::mValueAxis, QCPAbstractPlottable::name.
void QCPGraph::drawLegendIcon(QCPPainter *painter, const QRectF &rect) const
References QCPAbstractPlottable::applyDefaultAntialiasingHint, QCPAbstractPlottable::applyFillAntialiasingHint, QCPAbstractPlottable::applyScattersAntialiasingHint, QCPScatterStyle::applyTo, QCPPainter::drawLine, QCPScatterStyle::drawShape, QCPScatterStyle::isNone, lsNone, QCPAbstractPlottable::mBrush, mLineStyle, QCPAbstractPlottable::mPen, mScatterStyle, QCPScatterStyle::pixmap, QCPPainter::setPen, QCPScatterStyle::setPixmap, QCPScatterStyle::shape, QCPScatterStyle::ssPixmap.
QCPRange QCPGraph::getKeyRange(bool &foundRange, SignDomain inSignDomain=sdBoth) const
Referenced by rescaleKeyAxis.
QCPRange QCPGraph::getValueRange(bool &foundRange, SignDomain inSignDomain=sdBoth) const
Referenced by rescaleValueAxis.
QCPRange QCPGraph::getKeyRange(bool &foundRange, SignDomain inSignDomain, bool includeErrors) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Allows to specify whether the error bars should be included in the range calculation. getKeyRange(bool &foundRange, SignDomain inSignDomain)
References QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, QCPRange::upper.
QCPRange QCPGraph::getValueRange(bool &foundRange, SignDomain inSignDomain, bool includeErrors) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Allows to specify whether the error bars should be included in the range calculation. getValueRange(bool &foundRange, SignDomain inSignDomain)
References QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, QCPRange::upper.
void QCPGraph::drawFill(QCPPainter *painter, QVector< QPointF > *lineData) const
References addFillBasePoints, QCPAbstractPlottable::applyFillAntialiasingHint, getChannelFillPolygon, lsImpulse, QCPAbstractPlottable::mainBrush, mChannelFillGraph, mLineStyle, removeFillBasePoints, QCPPainter::setPen.
Referenced by draw.
void QCPGraph::drawScatterPlot(QCPPainter *painter, QVector< QCPData > *scatterData) const
References QCPAbstractPlottable::applyErrorBarsAntialiasingHint, QCPAbstractPlottable::applyScattersAntialiasingHint, QCPScatterStyle::applyTo, QCPAxis::coordToPixel, drawError, QCPScatterStyle::drawShape, etNone, QCPAbstractPlottable::keyAxis, mErrorPen, mErrorType, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mPen, mScatterStyle, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation, QCPPainter::setPen, QCPAbstractPlottable::valueAxis.
Referenced by draw.
void QCPGraph::drawLinePlot(QCPPainter *painter, QVector< QPointF > *lineData) const
References QCPAbstractPlottable::applyDefaultAntialiasingHint, QCPPainter::drawLine, QCPAbstractPlottable::mainPen, QCPPainter::modes, QCPLayerable::mParentPlot, QCP::phFastPolylines, QCustomPlot::plottingHints, QCPPainter::pmNoCaching, QCPPainter::pmVectorized, QCPPainter::setPen.
Referenced by draw.
void QCPGraph::drawImpulsePlot(QCPPainter *painter, QVector< QPointF > *lineData) const
References QCPAbstractPlottable::applyDefaultAntialiasingHint, QCPAbstractPlottable::mainPen, QCPAbstractPlottable::pen, QCPPainter::setPen.
Referenced by draw.
void QCPGraph::getPreparedData(QVector< QCPData > *lineData, QVector< QCPData > *scatterData) const
References QCPAxis::coordToPixel, countDataInBounds, getVisibleDataBounds, QCPAbstractPlottable::keyAxis, QCPRange::lower, mAdaptiveSampling, mData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation, QCPAxis::pixelToCoord, QCPAxis::range, QCPAxis::rangeReversed, QCPAxis::scaleType, QCPAxis::stLogarithmic, QCPRange::upper, QCPAbstractPlottable::valueAxis.
Referenced by getImpulsePlotData, getLinePlotData, getScatterPlotData, getStepCenterPlotData, getStepLeftPlotData, getStepRightPlotData.
void QCPGraph::getPlotData(QVector< QPointF > *lineData, QVector< QCPData > *scatterData) const
References getImpulsePlotData, getLinePlotData, getScatterPlotData, getStepCenterPlotData, getStepLeftPlotData, getStepRightPlotData, lsImpulse, lsLine, lsNone, lsStepCenter, lsStepLeft, lsStepRight, mLineStyle.
Referenced by draw, pointDistance.
void QCPGraph::getScatterPlotData(QVector< QCPData > *scatterData) const
References getPreparedData.
Referenced by getPlotData, pointDistance.
void QCPGraph::getLinePlotData(QVector< QPointF > *linePixelData, QVector< QCPData > *scatterData) const
References QCPAxis::coordToPixel, getPreparedData, QCPAbstractPlottable::keyAxis, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation, QCPAbstractPlottable::valueAxis.
Referenced by getPlotData.
void QCPGraph::getStepLeftPlotData(QVector< QPointF > *linePixelData, QVector< QCPData > *scatterData) const
References QCPAxis::coordToPixel, getPreparedData, QCPAbstractPlottable::keyAxis, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation, QCPAbstractPlottable::valueAxis.
Referenced by getPlotData.
void QCPGraph::getStepRightPlotData(QVector< QPointF > *linePixelData, QVector< QCPData > *scatterData) const
References QCPAxis::coordToPixel, getPreparedData, QCPAbstractPlottable::keyAxis, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation, QCPAbstractPlottable::valueAxis.
Referenced by getPlotData.
void QCPGraph::getStepCenterPlotData(QVector< QPointF > *linePixelData, QVector< QCPData > *scatterData) const
References QCPAxis::coordToPixel, getPreparedData, QCPAbstractPlottable::keyAxis, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation, QCPAbstractPlottable::valueAxis.
Referenced by getPlotData.
void QCPGraph::getImpulsePlotData(QVector< QPointF > *linePixelData, QVector< QCPData > *scatterData) const
References QCPAxis::coordToPixel, getPreparedData, QCPAbstractPlottable::keyAxis, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation, QCPAbstractPlottable::valueAxis.
Referenced by getPlotData.
void QCPGraph::drawError(QCPPainter *painter, double x, double y, const QCPData &data) const
References QCPAxis::coordToPixel, data, QCPPainter::drawLine, etBoth, etKey, etValue, QCPAbstractPlottable::keyAxis, mErrorBarSize, mErrorBarSkipSymbol, mErrorType, QCPAbstractPlottable::mKeyAxis, mScatterStyle, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation, QCPAxis::rangeReversed, QCPScatterStyle::size, QCPAbstractPlottable::valueAxis.
Referenced by drawScatterPlot.
void QCPGraph::getVisibleDataBounds(QCPDataMap::const_iterator &lower, QCPDataMap::const_iterator &upper) const
References mData, QCPAbstractPlottable::mKeyAxis.
Referenced by getPreparedData.
int QCPGraph::countDataInBounds(const QCPDataMap::const_iterator &lower, const QCPDataMap::const_iterator &upper, int maxCount) const
References mData.
Referenced by getPreparedData.
void QCPGraph::addFillBasePoints(QVector< QPointF > *lineData) const
References lowerFillBasePoint, QCPAbstractPlottable::mKeyAxis, upperFillBasePoint.
Referenced by drawFill.
void QCPGraph::removeFillBasePoints(QVector< QPointF > *lineData) const
Referenced by drawFill.
QPointF QCPGraph::lowerFillBasePoint(double lowerKey) const
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxis::axisRect, QCPAxis::axisType, QCPAxisRect::bottom, QCPAxis::coordToPixel, QCPAbstractPlottable::keyAxis, QCPAxisRect::left, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation, QCPAxis::range, QCPAxis::rangeReversed, QCPAxisRect::right, QCPAxis::scaleType, QCPAxis::stLinear, QCPAxisRect::top, QCPRange::upper, QCPAbstractPlottable::valueAxis.
Referenced by addFillBasePoints.
QPointF QCPGraph::upperFillBasePoint(double upperKey) const
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxis::axisRect, QCPAxis::axisType, QCPAxisRect::bottom, QCPAxis::coordToPixel, QCPAbstractPlottable::keyAxis, QCPAxisRect::left, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation, QCPAxis::range, QCPAxis::rangeReversed, QCPAxisRect::right, QCPAxis::scaleType, QCPAxis::stLinear, QCPAxisRect::top, QCPRange::upper, QCPAbstractPlottable::valueAxis.
Referenced by addFillBasePoints.
const QPolygonF QCPGraph::getChannelFillPolygon(const QVector< QPointF > *lineData) const
References findIndexAboveX, findIndexAboveY, findIndexBelowX, findIndexBelowY, QCPAbstractPlottable::keyAxis, mChannelFillGraph, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation, QCPAbstractPlottable::valueAxis.
Referenced by drawFill.
int QCPGraph::findIndexBelowX(const QVector< QPointF > *data, double x) const
References data.
Referenced by getChannelFillPolygon.
int QCPGraph::findIndexAboveX(const QVector< QPointF > *data, double x) const
References data.
Referenced by getChannelFillPolygon.
int QCPGraph::findIndexBelowY(const QVector< QPointF > *data, double y) const
References data.
Referenced by getChannelFillPolygon.
int QCPGraph::findIndexAboveY(const QVector< QPointF > *data, double y) const
References data.
Referenced by getChannelFillPolygon.
double QCPGraph::pointDistance(const QPointF &pixelPoint) const
References QCPAbstractPlottable::coordsToPixels, QCPAbstractPlottable::distSqrToLine, getPlotData, getScatterPlotData, QCPScatterStyle::isNone, lsImpulse, lsNone, mData, mLineStyle, mScatterStyle.
Referenced by selectTest.