Simulator
bool Simulator::running
Referenced by Finish, GetTimerElapsed, isRunning, Start, Stop, Tick.
shared_ptr<Map> Simulator::map
Referenced by PlotMap, SetMap, Simulator, Tick.
shared_ptr<Mouse> Simulator::mouse
Referenced by PlotMouse, SetSpeed, Simulator, Tick.
SI* Simulator::si
Referenced by Simulator.
HumanControll* Simulator::controll
Referenced by ControllDirection, Simulator.
QCustomPlot* Simulator::plot
Referenced by DrawLine, DrawMouseCircle, DrawMouseLine, PlotMap, Simulator, Tick.
shared_ptr<QElapsedTimer> Simulator::timer
Referenced by Finish, GetTimerElapsed, Start, Stop.
quint64 Simulator::timeElapsed
Referenced by Finish, Stop.
int Simulator::si_mode
Referenced by ControllDirection.
QVector<double> Simulator::mouseBodyX
Referenced by PlotMouse.
QVector<double> Simulator::mouseBodyY
Referenced by PlotMouse.
QVector<double> Simulator::mouseHeadX
Referenced by PlotMouse.
QVector<double> Simulator::mouseHeadY
Referenced by PlotMouse.
QVector<double> Simulator::mouseTailX
Referenced by PlotMouse.
QVector<double> Simulator::mouseTailY
Referenced by PlotMouse.
QCPGraph* Simulator::mouseBody
Referenced by PlotMouse.
QCPGraph * Simulator::mouseHead
Referenced by PlotMouse.
QCPGraph * Simulator::mouseTail
Referenced by PlotMouse.
Simulator::Simulator(QCustomPlot *_plot, string mapFilePath, int _speed, int _si_mode)
Construct a new Simulator object.
_plot mapFilePath _speed _si_mode
References controll, map, mouse, plot, PlotMap, PlotMouse, QCustomPlot::replot, SetMap, si, Up.
Simulator::Simulator()
Construct a new Simulator object.
Simulator::~Simulator()
Destroy the Simulator object.
void Simulator::Start()
Start simulation.
References running, timer.
Referenced by GetTimerElapsed.
void Simulator::Stop()
Stop simulation.
References running, timeElapsed, timer.
void Simulator::Tick()
Single tick (step) of simulation.
References Finish, map, mouse, plot, PlotMouse, QCustomPlot::replot, running.
void Simulator::SetSpeed(int _speed)
Set the Speed object.
_speed
References mouse.
quint64 Simulator::GetTimerElapsed()
Get the Timer Elapsed object.
quint64
References running, Start, timer.
void Simulator::ControllDirection(Direction d)
Human controll set direction.
d
References controll, HumanControll::SetDirection, si_mode.
bool Simulator::isRunning()
Is simulation running?
true false
References running.
bool Simulator::SetMap(string mapFilePath)
References map.
Referenced by Simulator.
void Simulator::Loop()
void Simulator::PlotMap()
References BLACK, DrawLine, GetPathLines, GRAY, GREEN, map, plot, QCPAxis::setRange, QCPAxis::setScaleRatio, QCustomPlot::xAxis, QCustomPlot::yAxis.
Referenced by Simulator.
void Simulator::PlotMouse(bool init=false)
References BLUE, QCPGraph::data, Down, DrawMouseCircle, DrawMouseLine, GRAY, Left, mouse, mouseBody, mouseBodyX, mouseBodyY, mouseHead, mouseHeadX, mouseHeadY, mouseTail, mouseTailX, mouseTailY, Right, QCPGraph::setData, Up.
Referenced by Simulator, Tick.
void Simulator::PlotSI()
void Simulator::Finish()
References running, timeElapsed, timer.
Referenced by Tick.
QCPGraph * Simulator::DrawLine(Line< double > line, const QColor color=GRAY, const int width=2)
References Line< T >::a, QCustomPlot::addGraph, Line< T >::b, plot, QCPAbstractPlottable::setPen.
Referenced by DrawRectangle, PlotMap.
QCPGraph * Simulator::DrawMouseCircle(QVector< double > &x, QVector< double > &y, const QColor color, const int width)
References QCustomPlot::addGraph, plot, QCPAbstractPlottable::setPen, QCPScatterStyle::ssCircle.
Referenced by PlotMouse.
QCPGraph * Simulator::DrawMouseLine(QVector< double > &x, QVector< double > &y, const QColor color, const int width)
References QCustomPlot::addGraph, plot, QCPAbstractPlottable::setPen.
Referenced by PlotMouse.
vector< QCPGraph * > Simulator::DrawRectangle(Point< T > point, const QColor color=GRAY, const int width=1, const double margin=0.1, const int step=1)
References DrawLine, Point< T >::x, Point< T >::y.