QCPAbstractItem
bool QCPAbstractItem::mClipToAxisRect
Referenced by clipRect, setClipAxisRect, setClipToAxisRect.
QPointer<QCPAxisRect> QCPAbstractItem::mClipAxisRect
Referenced by clipAxisRect, clipRect, setClipAxisRect, setClipToAxisRect.
QList<QCPItemPosition*> QCPAbstractItem::mPositions
Referenced by createPosition, position.
QList<QCPItemAnchor*> QCPAbstractItem::mAnchors
Referenced by anchor, createAnchor, createPosition, hasAnchor, ~QCPAbstractItem.
bool QCPAbstractItem::mSelectable
Referenced by deselectEvent, selectEvent, QCPItemStraightLine::selectTest, QCPItemLine::selectTest, QCPItemCurve::selectTest, QCPItemRect::selectTest, QCPItemText::selectTest, QCPItemEllipse::selectTest, QCPItemPixmap::selectTest, QCPItemTracer::selectTest, QCPItemBracket::selectTest, setSelectable.
bool QCPAbstractItem::mSelected
Referenced by deselectEvent, QCPItemRect::mainBrush, QCPItemText::mainBrush, QCPItemEllipse::mainBrush, QCPItemTracer::mainBrush, QCPItemText::mainColor, QCPItemText::mainFont, QCPItemStraightLine::mainPen, QCPItemLine::mainPen, QCPItemCurve::mainPen, QCPItemRect::mainPen, QCPItemText::mainPen, QCPItemEllipse::mainPen, QCPItemPixmap::mainPen, QCPItemTracer::mainPen, QCPItemBracket::mainPen, selectEvent, setSelected.
friend class QCustomPlot
friend class QCPItemAnchor
Referenced by createAnchor.
QCPAbstractItem::QCPAbstractItem(QCustomPlot *parentPlot)
Base class constructor which initializes base class members.
References QCustomPlot::axisRects, QCPLayerable::parentPlot, setClipAxisRect, setClipToAxisRect.
QCPAbstractItem::~QCPAbstractItem()
References mAnchors.
bool QCPAbstractItem::clipToAxisRect() const
Referenced by QCustomPlot::itemAt.
QCPAxisRect * QCPAbstractItem::clipAxisRect() const
References mClipAxisRect.
bool QCPAbstractItem::selectable() const
Referenced by QCustomPlot::itemAt, setSelectable.
bool QCPAbstractItem::selected() const
Referenced by QCustomPlot::selectedItems, setSelected.
void QCPAbstractItem::setClipToAxisRect(bool clip)
Sets whether the item shall be clipped to an axis rect or whether it shall be visible on the entire QCustomPlot. The axis rect can be set with setClipAxisRect. setClipAxisRect
References mClipAxisRect, mClipToAxisRect, QCPLayerable::setParentLayerable.
Referenced by QCPAbstractItem.
void QCPAbstractItem::setClipAxisRect(QCPAxisRect *rect)
Sets the clip axis rect. It defines the rect that will be used to clip the item when setClipToAxisRect is set to true. setClipToAxisRect
References mClipAxisRect, mClipToAxisRect, QCPLayerable::setParentLayerable.
Referenced by QCPAbstractItem.
void QCPAbstractItem::setSelectable(bool selectable)
Sets whether the user can (de-)select this item by clicking on the QCustomPlot surface. (When QCustomPlot::setInteractions contains QCustomPlot::iSelectItems.) However, even when selectable was set to false, it is possible to set the selection manually, by calling setSelected. QCustomPlot::setInteractions, setSelected
References mSelectable, selectable, selectableChanged.
void QCPAbstractItem::setSelected(bool selected)
Sets whether this item is selected or not. When selected, it might use a different visual appearance (e.g. pen and brush), this depends on the specific item though. The entire selection mechanism for items is handled automatically when QCustomPlot::setInteractions contains QCustomPlot::iSelectItems. You only need to call this function when you wish to change the selection state manually. This function can change the selection state even when setSelectable was set to false. emits the selectionChanged signal when selected is different from the previous selection state. setSelectable, selectTest
References mSelected, selected, selectionChanged.
Referenced by deselectEvent, selectEvent.
virtual double QCPAbstractItem::selectTest(const QPointF &pos, bool onlySelectable, QVariant *details=0) const =0
This function is used to decide whether a click hits a layerable object or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too. If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99). Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance). The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods. details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation. You may pass 0 as details to indicate that you are not interested in those selection details. selectEvent, deselectEvent, QCustomPlot::setInteractions
Referenced by QCustomPlot::itemAt.
QList< QCPItemPosition * > QCPAbstractItem::positions() const
Returns all positions of the item in a list. anchors, position
QList< QCPItemAnchor * > QCPAbstractItem::anchors() const
Returns all anchors of the item in a list. Note that since a position (QCPItemPosition) is always also an anchor, the list will also contain the positions of this item. positions, anchor
QCPItemPosition * QCPAbstractItem::position(const QString &name) const
Returns the QCPItemPosition with the specified name. If this item doesn't have a position by that name, returns 0. This function provides an alternative way to access item positions. Normally, you access positions direcly by their member pointers (which typically have the same variable name as name). positions, anchor
References mPositions.
QCPItemAnchor * QCPAbstractItem::anchor(const QString &name) const
Returns the QCPItemAnchor with the specified name. If this item doesn't have an anchor by that name, returns 0. This function provides an alternative way to access item anchors. Normally, you access anchors direcly by their member pointers (which typically have the same variable name as name). anchors, position
References mAnchors.
bool QCPAbstractItem::hasAnchor(const QString &name) const
Returns whether this item has an anchor with the specified name. Note that you can check for positions with this function, too. This is because every position is also an anchor (QCPItemPosition inherits from QCPItemAnchor). anchor, position
References mAnchors.
Referenced by createAnchor, createPosition.
void QCPAbstractItem::selectionChanged(bool selected)
This signal is emitted when the selection state of this item has changed, either by user interaction or by a direct call to setSelected.
Referenced by setSelected.
void QCPAbstractItem::selectableChanged(bool selectable)
Referenced by setSelectable.
QCP::Interaction QCPAbstractItem::selectionCategory() const
References QCP::iSelectItems.
QRect QCPAbstractItem::clipRect() const
References mClipAxisRect, mClipToAxisRect, QCPLayerable::mParentPlot, QCustomPlot::viewport.
Referenced by QCPItemStraightLine::draw, QCPItemLine::draw, QCPItemCurve::draw, QCPItemRect::draw, QCPItemText::draw, QCPItemEllipse::draw, QCPItemPixmap::draw, QCPItemTracer::draw, QCPItemBracket::draw, QCustomPlot::itemAt, QCPItemTracer::selectTest.
void QCPAbstractItem::applyDefaultAntialiasingHint(QCPPainter *painter) const
References QCP::aeItems, QCPLayerable::applyAntialiasingHint, QCPLayerable::mAntialiased.
void QCPAbstractItem::draw(QCPPainter *painter)=0
void QCPAbstractItem::selectEvent(QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
References mSelectable, mSelected, setSelected.
void QCPAbstractItem::deselectEvent(bool *selectionStateChanged)
References mSelectable, mSelected, setSelected.
QPointF QCPAbstractItem::anchorPixelPoint(int anchorId) const
Referenced by QCPItemAnchor::pixelPoint.
double QCPAbstractItem::distSqrToLine(const QPointF &start, const QPointF &end, const QPointF &point) const
Referenced by rectSelectTest, QCPItemLine::selectTest, QCPItemCurve::selectTest, QCPItemTracer::selectTest, QCPItemBracket::selectTest.
double QCPAbstractItem::rectSelectTest(const QRectF &rect, const QPointF &pos, bool filledRect) const
References distSqrToLine, QCPLayerable::mParentPlot, QCustomPlot::selectionTolerance.
Referenced by QCPItemRect::selectTest, QCPItemText::selectTest, QCPItemPixmap::selectTest, QCPItemTracer::selectTest.
QCPItemPosition * QCPAbstractItem::createPosition(const QString &name)
References QCustomPlot::axisRect, hasAnchor, mAnchors, QCPLayerable::mParentPlot, mPositions, QCPItemPosition::ptPlotCoords, QCPItemPosition::setAxes, QCPItemPosition::setAxisRect, QCPItemPosition::setCoords, QCPItemPosition::setType, QCustomPlot::xAxis, QCustomPlot::yAxis.
QCPItemAnchor * QCPAbstractItem::createAnchor(const QString &name, int anchorId)
References hasAnchor, mAnchors, QCPLayerable::mParentPlot, QCPItemAnchor.