SI
SI::SI()
Construct a new SI object.
Task SI::Call(SensorData sensorData)
Call SI to get task.
sensorData Task
References Logic.
Referenced by Mouse::Call.
Task SI::Logic(SensorData sensorData)
Logic implementation.
sensorData Task
References RandomTask.
Referenced by Call.
Task SI::RandomTask(SensorData sensorData)
References Forward, RotateLeft, RotateRight, TurnAround, SensorData::wallDetected.
Referenced by Logic.