MainWindow
Ui::MainWindow* MainWindow::ui
Referenced by InitSimulator, MainWindow, simulator_plot, ~MainWindow.
shared_ptr<Simulator> MainWindow::simulator
Referenced by InitSimulator, keyPressEvent, on_mapsComboBox_textActivated, on_speedSlider_valueChanged, on_startButton_clicked, simulator_plot.
QTimer* MainWindow::timer
Referenced by on_startButton_clicked, on_stopButton_clicked.
double MainWindow::time_seconds
Referenced by InitSimulator, simulator_plot.
MainWindow::MainWindow(QWidget *parent=nullptr, shared_ptr< Simulator > _simulator=nullptr)
Construct a new Main Window object.
parent _simulator
References GetMapFiles, InitSimulator, ui.
MainWindow::~MainWindow()
Destroy the Main Window object.
References ui.
void MainWindow::on_mapsComboBox_textActivated(const QString &arg1)
References InitSimulator, simulator.
void MainWindow::on_startButton_clicked()
References InitSimulator, simulator, simulator_plot, timer.
void MainWindow::on_stopButton_clicked()
References InitSimulator, timer.
void MainWindow::simulator_plot()
References simulator, time_seconds, ui.
Referenced by on_startButton_clicked.
void MainWindow::on_speedSlider_valueChanged(int value)
References simulator.
void MainWindow::keyPressEvent(QKeyEvent *event) override
keyboard key events handles
event
References Down, Left, Right, simulator, Up.
void MainWindow::InitSimulator()
References MAPS_LOCATION, simulator, time_seconds, ui.
Referenced by MainWindow, on_mapsComboBox_textActivated, on_startButton_clicked, on_stopButton_clicked.
void MainWindow::PlotMap()
QCPGraph* MainWindow::DrawLine(double x0, double y0, double x1, double y1)