QCPAxisPainterPrivate
QCPAxis::AxisType QCPAxisPainterPrivate::type
Referenced by QCPAxis::calculateMargin, QCPAxis::draw, draw, getTickLabelDrawOffset, placeTickLabel, size.
QPen QCPAxisPainterPrivate::basePen
Referenced by QCPAxis::draw, draw.
QCPLineEnding QCPAxisPainterPrivate::lowerEnding
Referenced by draw, QCPAxis::lowerEnding, QCPAxis::setLowerEnding.
QCPLineEnding QCPAxisPainterPrivate::upperEnding
Referenced by draw, QCPAxis::setUpperEnding, QCPAxis::upperEnding.
int QCPAxisPainterPrivate::labelPadding
Referenced by draw, QCPAxis::labelPadding, QCPAxis::setLabelPadding, size.
QFont QCPAxisPainterPrivate::labelFont
Referenced by QCPAxis::calculateMargin, QCPAxis::draw, draw, size.
QColor QCPAxisPainterPrivate::labelColor
Referenced by QCPAxis::draw, draw.
QString QCPAxisPainterPrivate::label
Referenced by QCPAxis::calculateMargin, QCPAxis::draw, draw, size.
int QCPAxisPainterPrivate::tickLabelPadding
Referenced by draw, QCPAxis::setTickLabelPadding, size, QCPAxis::tickLabelPadding.
double QCPAxisPainterPrivate::tickLabelRotation
Referenced by drawTickLabel, generateLabelParameterHash, getTickLabelData, getTickLabelDrawOffset, QCPAxis::setTickLabelRotation, QCPAxis::tickLabelRotation.
QCPAxis::LabelSide QCPAxisPainterPrivate::tickLabelSide
Referenced by draw, generateLabelParameterHash, getTickLabelDrawOffset, placeTickLabel, QCPAxis::setTickLabelSide, size, QCPAxis::tickLabelSide.
bool QCPAxisPainterPrivate::substituteExponent
Referenced by QCPAxis::draw, generateLabelParameterHash, getTickLabelData.
bool QCPAxisPainterPrivate::numberMultiplyCross
Referenced by generateLabelParameterHash, getTickLabelData, QCPAxis::numberFormat, QCPAxis::setNumberFormat.
int QCPAxisPainterPrivate::tickLengthIn
Referenced by draw, QCPAxis::setTickLengthIn, QCPAxis::tickLengthIn.
int QCPAxisPainterPrivate::tickLengthOut
Referenced by draw, QCPAxis::setTickLengthOut, size, QCPAxis::tickLengthOut.
int QCPAxisPainterPrivate::subTickLengthIn
Referenced by draw, QCPAxis::setSubTickLengthIn, QCPAxis::subTickLengthIn.
int QCPAxisPainterPrivate::subTickLengthOut
Referenced by draw, QCPAxis::setSubTickLengthOut, size, QCPAxis::subTickLengthOut.
QPen QCPAxisPainterPrivate::tickPen
Referenced by QCPAxis::draw, draw.
QPen QCPAxisPainterPrivate::subTickPen
Referenced by QCPAxis::draw, draw.
QFont QCPAxisPainterPrivate::tickLabelFont
Referenced by QCPAxis::calculateMargin, QCPAxis::draw, draw, generateLabelParameterHash, size.
QColor QCPAxisPainterPrivate::tickLabelColor
Referenced by QCPAxis::draw, draw, generateLabelParameterHash.
QRect QCPAxisPainterPrivate::axisRect
Referenced by QCPAxis::calculateMargin, QCPAxis::draw, draw, placeTickLabel.
QRect QCPAxisPainterPrivate::viewportRect
Referenced by QCPAxis::calculateMargin, QCPAxis::draw, placeTickLabel.
double QCPAxisPainterPrivate::offset
Referenced by draw, QCPAxis::offset, placeTickLabel, QCPAxis::setOffset.
bool QCPAxisPainterPrivate::abbreviateDecimalPowers
Referenced by QCPAxis::draw, getTickLabelData.
bool QCPAxisPainterPrivate::reversedEndings
Referenced by QCPAxis::draw, draw.
QVector<double> QCPAxisPainterPrivate::subTickPositions
Referenced by QCPAxis::draw, draw.
QVector<double> QCPAxisPainterPrivate::tickPositions
Referenced by QCPAxis::calculateMargin, QCPAxis::draw, draw, size.
QVector<QString> QCPAxisPainterPrivate::tickLabels
Referenced by QCPAxis::calculateMargin, QCPAxis::draw, draw, size.
QCustomPlot* QCPAxisPainterPrivate::mParentPlot
Referenced by draw, getMaxTickLabelSize, placeTickLabel.
QByteArray QCPAxisPainterPrivate::mLabelParameterHash
Referenced by draw.
QCache<QString, CachedLabel> QCPAxisPainterPrivate::mLabelCache
Referenced by clearCache, draw, getMaxTickLabelSize, placeTickLabel.
QRect QCPAxisPainterPrivate::mAxisSelectionBox
Referenced by draw.
QRect QCPAxisPainterPrivate::mTickLabelsSelectionBox
Referenced by draw.
QRect QCPAxisPainterPrivate::mLabelSelectionBox
Referenced by draw.
QCPAxisPainterPrivate::QCPAxisPainterPrivate(QCustomPlot *parentPlot)
Constructs a QCPAxisPainterPrivate instance. Make sure to not create a new instance on every redraw, to utilize the caching mechanisms.
QCPAxisPainterPrivate::~QCPAxisPainterPrivate()
void QCPAxisPainterPrivate::draw(QCPPainter *painter)
References QCPPainter::antialiasing, QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, axisRect, basePen, QCPLineEnding::draw, QCPPainter::drawLine, QCPLineEnding::esNone, generateLabelParameterHash, QCPLineEnding::inverted, label, labelColor, labelFont, labelPadding, lowerEnding, QCPAxis::lsInside, QCPAxis::lsOutside, mAxisSelectionBox, mLabelCache, mLabelParameterHash, mLabelSelectionBox, mParentPlot, mTickLabelsSelectionBox, offset, QCPAxis::orientation, placeTickLabel, QCPLineEnding::realLength, reversedEndings, QCustomPlot::selectionTolerance, QCPPainter::setAntialiasing, QCPPainter::setPen, QCPLineEnding::style, subTickLengthIn, subTickLengthOut, subTickPen, subTickPositions, tickLabelColor, tickLabelFont, tickLabelPadding, tickLabels, tickLabelSide, tickLengthIn, tickLengthOut, tickPen, tickPositions, type, upperEnding.
Referenced by QCPAxis::draw.
int QCPAxisPainterPrivate::size() const
References getMaxTickLabelSize, label, labelFont, labelPadding, QCPAxis::lsOutside, QCPAxis::orientation, subTickLengthOut, tickLabelFont, tickLabelPadding, tickLabels, tickLabelSide, tickLengthOut, tickPositions, type.
Referenced by QCPAxis::calculateMargin.
void QCPAxisPainterPrivate::clearCache()
References mLabelCache.
QRect QCPAxisPainterPrivate::axisSelectionBox() const
Referenced by QCPAxis::getPartAt.
QRect QCPAxisPainterPrivate::tickLabelsSelectionBox() const
Referenced by QCPAxis::getPartAt.
QRect QCPAxisPainterPrivate::labelSelectionBox() const
Referenced by QCPAxis::getPartAt.
QByteArray QCPAxisPainterPrivate::generateLabelParameterHash() const
References numberMultiplyCross, substituteExponent, tickLabelColor, tickLabelFont, tickLabelRotation, tickLabelSide.
Referenced by draw.
void QCPAxisPainterPrivate::placeTickLabel(QCPPainter *painter, double position, int distanceToAxis, const QString &text, QSize *tickLabelsSize)
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, axisRect, drawTickLabel, getTickLabelData, getTickLabelDrawOffset, QCPAxis::lsOutside, mLabelCache, QCPPainter::modes, mParentPlot, offset, QCPAxisPainterPrivate::CachedLabel::offset, QCPAxis::orientation, QCP::phCacheLabels, QCPAxisPainterPrivate::CachedLabel::pixmap, QCustomPlot::plottingHints, QCPPainter::pmNoCaching, QCPAxisPainterPrivate::TickLabelData::rotatedTotalBounds, QCPPainter::setPen, tickLabelSide, type, viewportRect.
Referenced by draw.
void QCPAxisPainterPrivate::drawTickLabel(QCPPainter *painter, double x, double y, const TickLabelData &labelData) const
References QCPAxisPainterPrivate::TickLabelData::baseBounds, QCPAxisPainterPrivate::TickLabelData::baseFont, QCPAxisPainterPrivate::TickLabelData::basePart, QCPAxisPainterPrivate::TickLabelData::expBounds, QCPAxisPainterPrivate::TickLabelData::expFont, QCPAxisPainterPrivate::TickLabelData::expPart, tickLabelRotation, QCPAxisPainterPrivate::TickLabelData::totalBounds.
Referenced by placeTickLabel.
QCPAxisPainterPrivate::TickLabelData QCPAxisPainterPrivate::getTickLabelData(const QFont &font, const QString &text) const
References abbreviateDecimalPowers, QCPAxisPainterPrivate::TickLabelData::baseBounds, QCPAxisPainterPrivate::TickLabelData::baseFont, QCPAxisPainterPrivate::TickLabelData::basePart, QCPAxisPainterPrivate::TickLabelData::expBounds, QCPAxisPainterPrivate::TickLabelData::expFont, QCPAxisPainterPrivate::TickLabelData::expPart, numberMultiplyCross, QCPAxisPainterPrivate::TickLabelData::rotatedTotalBounds, substituteExponent, tickLabelRotation, QCPAxisPainterPrivate::TickLabelData::totalBounds.
Referenced by getMaxTickLabelSize, placeTickLabel.
QPointF QCPAxisPainterPrivate::getTickLabelDrawOffset(const TickLabelData &labelData) const
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxis::lsInside, QCPAxis::lsOutside, tickLabelRotation, tickLabelSide, QCPAxisPainterPrivate::TickLabelData::totalBounds, type.
Referenced by placeTickLabel.
void QCPAxisPainterPrivate::getMaxTickLabelSize(const QFont &font, const QString &text, QSize *tickLabelsSize) const
References getTickLabelData, mLabelCache, mParentPlot, QCP::phCacheLabels, QCPAxisPainterPrivate::CachedLabel::pixmap, QCustomPlot::plottingHints, QCPAxisPainterPrivate::TickLabelData::rotatedTotalBounds.
Referenced by size.