Map
vector<Path<int> > Map::mapPaths
list of known paths in map
Referenced by FindPath, InsertPaths, Map.
Point<int> Map::mapStart
map start point (x,y)
Referenced by Map.
Point<int> Map::mapSize
map size (w,h)
Referenced by Map.
vector<Point<int> > Map::mapStop
vector ofmap stop points (x,y)
Referenced by Map.
Map::Map(string mapFilePath)
Construct a new Map object.
mapFilePath
References InsertPaths, MAP_PATHS_SIGN, MAP_SIZE_SIGN, MAP_START_SIGN, MAP_STOP_SIGN, mapPaths, mapSize, mapStart, mapStop.
Map::Map()
Construct a new Map object.
Map::~Map()
Destroy the Map object.
const Path< int > Map::FindPathConst(Point< int > localization)
Get const path by localization.
localization const Path<int>
References FindPath.
shared_ptr< Path< T > > Map::FindPath(Point< T > localization)
Get path ptr by localization.
T localization shared_ptr<Path<T>>
References mapPaths.
Referenced by FindPathConst, FindPaths.
vector< shared_ptr< Path< T > > > Map::FindPaths(vector< Point< T >> localizations)
Get vector of paths by localizations in vector.
T localizations vector<shared_ptr<Path<T>>>
References FindPath.
Referenced by UpdateConnections.
void Map::InsertPaths(vector< Path< int >> newPaths)
Insert new path in structure.
newPaths
References mapPaths.
Referenced by Map.
vector< Point< T > > Map::FindNearLocalizations(Point< T > localization)
Find near localizations of specyfic localization (x,y)
T localization vector<Point<T>>
References Point< T >::x, Point< T >::y.
void Map::UpdateConnections(shared_ptr< Path< int >> path)
Update/refresh connections in specyfic paths.
path
References Allowed, FindPaths.
vector< Path< T > > Map::GetPaths(string line)
References Allowed, Path< T >::localization, SplitText, Point< T >::x, Point< T >::y.
vector< string > Map::SplitText(string text, char delimiter)
Referenced by GetPaths, GetPoint.
Point< T > Map::GetPoint(string text, char delimiter)
References SplitText, Point< T >::x, Point< T >::y.