QCPColorMapData
int QCPColorMapData::mKeySize
Referenced by cell, cellToCoord, coordToCell, data, fill, recalculateDataBounds, setCell, setData, setSize, setValueSize.
int QCPColorMapData::mValueSize
Referenced by cell, cellToCoord, coordToCell, data, fill, recalculateDataBounds, setCell, setData, setKeySize, setSize.
QCPRange QCPColorMapData::mKeyRange
Referenced by cellToCoord, coordToCell, data, setData, setKeyRange.
QCPRange QCPColorMapData::mValueRange
Referenced by cellToCoord, coordToCell, data, setData, setValueRange.
bool QCPColorMapData::mIsEmpty
Referenced by operator=, setSize.
double* QCPColorMapData::mData
Referenced by cell, data, fill, operator=, recalculateDataBounds, setCell, setData, setSize, QCPColorMap::updateMapImage, ~QCPColorMapData.
QCPRange QCPColorMapData::mDataBounds
Referenced by fill, operator=, recalculateDataBounds, setCell, setData.
bool QCPColorMapData::mDataModified
Referenced by QCPColorMap::draw, fill, operator=, setCell, setData, setSize, QCPColorMap::updateMapImage.
friend class QCPColorMap
QCPColorMapData::QCPColorMapData(int keySize, int valueSize, const QCPRange &keyRange, const QCPRange &valueRange)
Constructs a new QCPColorMapData instance. The instance has keySize cells in the key direction and valueSize cells in the value direction. These cells will be displayed by the QCPColorMap at the coordinates keyRange and valueRange. setSize, setKeySize, setValueSize, setRange, setKeyRange, setValueRange
References fill, keySize, setSize, valueSize.
QCPColorMapData::~QCPColorMapData()
References mData.
QCPColorMapData::QCPColorMapData(const QCPColorMapData &other)
Constructs a new QCPColorMapData instance copying the data and range of other.
QCPColorMapData & QCPColorMapData::operator=(const QCPColorMapData &other)
Overwrites this color map data instance with the data stored in other.
References keyRange, keySize, mData, mDataBounds, mDataModified, mIsEmpty, setRange, setSize, valueRange, valueSize.
int QCPColorMapData::keySize() const
Referenced by QCPColorMap::draw, operator=, QCPColorMapData, setKeySize, setSize, QCPColorMap::updateMapImage.
int QCPColorMapData::valueSize() const
Referenced by QCPColorMap::draw, operator=, QCPColorMapData, setSize, setValueSize, QCPColorMap::updateMapImage.
QCPRange QCPColorMapData::keyRange() const
Referenced by QCPColorMap::draw, QCPColorMap::getKeyRange, operator=, QCPColorMap::selectTest, setKeyRange, setRange.
QCPRange QCPColorMapData::valueRange() const
Referenced by QCPColorMap::draw, QCPColorMap::getValueRange, operator=, QCPColorMap::selectTest, setRange, setValueRange.
QCPRange QCPColorMapData::dataBounds() const
Referenced by QCPColorMap::rescaleDataRange.
double QCPColorMapData::data(double key, double value)
References QCPRange::lower, mData, mKeyRange, mKeySize, mValueRange, mValueSize, QCPRange::upper.
double QCPColorMapData::cell(int keyIndex, int valueIndex)
References mData, mKeySize, mValueSize.
void QCPColorMapData::setSize(int keySize, int valueSize)
Resizes the data array to have keySize cells in the key dimension and valueSize cells in the value dimension. The current data is discarded and the map cells are set to 0, unless the map had already the requested size. Setting at least one of keySize or valueSize to zero frees the internal data array and isEmpty returns true. setRange, setKeySize, setValueSize
References fill, keySize, mData, mDataModified, mIsEmpty, mKeySize, mValueSize, valueSize.
Referenced by clear, operator=, QCPColorMapData, setKeySize, setValueSize.
void QCPColorMapData::setKeySize(int keySize)
Resizes the data array to have keySize cells in the key dimension. The current data is discarded and the map cells are set to 0, unless the map had already the requested size. Setting keySize to zero frees the internal data array and isEmpty returns true. setKeyRange, setSize, setValueSize
References keySize, mValueSize, setSize.
void QCPColorMapData::setValueSize(int valueSize)
Resizes the data array to have valueSize cells in the value dimension. The current data is discarded and the map cells are set to 0, unless the map had already the requested size. Setting valueSize to zero frees the internal data array and isEmpty returns true. setValueRange, setSize, setKeySize
References mKeySize, setSize, valueSize.
void QCPColorMapData::setRange(const QCPRange &keyRange, const QCPRange &valueRange)
Sets the coordinate ranges the data shall be distributed over. This defines the rectangular area covered by the color map in plot coordinates. The outer cells will be centered on the range boundaries given to this function. For example, if the key size (setKeySize) is 3 and keyRange is set to QCPRange(2, 3) there will be cells centered on the key coordinates 2, 2.5 and 3. setSize
References keyRange, setKeyRange, setValueRange, valueRange.
Referenced by operator=.
void QCPColorMapData::setKeyRange(const QCPRange &keyRange)
Sets the coordinate range the data shall be distributed over in the key dimension. Together with the value range, This defines the rectangular area covered by the color map in plot coordinates. The outer cells will be centered on the range boundaries given to this function. For example, if the key size (setKeySize) is 3 and keyRange is set to QCPRange(2, 3) there will be cells centered on the key coordinates 2, 2.5 and 3. setRange, setValueRange, setSize
References keyRange, mKeyRange.
Referenced by setRange.
void QCPColorMapData::setValueRange(const QCPRange &valueRange)
Sets the coordinate range the data shall be distributed over in the value dimension. Together with the key range, This defines the rectangular area covered by the color map in plot coordinates. The outer cells will be centered on the range boundaries given to this function. For example, if the value size (setValueSize) is 3 and valueRange is set to QCPRange(2, 3) there will be cells centered on the value coordinates 2, 2.5 and 3. setRange, setKeyRange, setSize
References mValueRange, valueRange.
Referenced by setRange.
void QCPColorMapData::setData(double key, double value, double z)
Sets the data of the cell, which lies at the plot coordinates given by key and value, to z. The QCPColorMap always displays the data at equal key/value intervals, even if the key or value axis is set to a logarithmic scaling. If you want to use QCPColorMap with logarithmic axes, you shouldn't use the QCPColorMapData::setData method as it uses a linear transformation to determine the cell index. Rather directly access the cell index with QCPColorMapData::setCell. setCell, setRange
References QCPRange::lower, mData, mDataBounds, mDataModified, mKeyRange, mKeySize, mValueRange, mValueSize, QCPRange::upper.
void QCPColorMapData::setCell(int keyIndex, int valueIndex, double z)
Sets the data of the cell with indices keyIndex and valueIndex to z. The indices enumerate the cells starting from zero, up to the map's size-1 in the respective dimension (see setSize). In the standard plot configuration (horizontal key axis and vertical value axis, both not range-reversed), the cell with indices (0, 0) is in the bottom left corner and the cell with indices (keySize-1, valueSize-1) is in the top right corner of the color map. setData, setSize
References QCPRange::lower, mData, mDataBounds, mDataModified, mKeySize, mValueSize, QCPRange::upper.
void QCPColorMapData::recalculateDataBounds()
Goes through the data and updates the buffered minimum and maximum data values. Calling this method is only advised if you are about to call QCPColorMap::rescaleDataRange and can not guarantee that the cells holding the maximum or minimum data haven't been overwritten with a smaller or larger value respectively, since the buffered maximum/minimum values have been updated the last time. Why this is the case is explained in the class description (QCPColorMapData). Note that the method QCPColorMap::rescaleDataRange provides a parameter recalculateDataBounds for convenience. Setting this to true will call this method for you, before doing the rescale.
References QCPRange::lower, mData, mDataBounds, mKeySize, mValueSize, QCPRange::upper.
Referenced by QCPColorMap::rescaleDataRange.
void QCPColorMapData::clear()
Frees the internal data memory. This is equivalent to calling setSize(0, 0).
References setSize.
Referenced by QCPColorMap::clearData.
void QCPColorMapData::fill(double z)
Sets all cells to the value z.
References mData, mDataBounds, mDataModified, mKeySize, mValueSize.
Referenced by QCPColorMapData, setSize.
bool QCPColorMapData::isEmpty() const
Returns whether this instance carries no data. This is equivalent to having a size where at least one of the dimensions is 0 (see setSize).
Referenced by QCPColorMap::draw, QCPColorMap::updateMapImage.
void QCPColorMapData::coordToCell(double key, double value, int *keyIndex, int *valueIndex) const
Transforms plot coordinates given by key and value to cell indices of this QCPColorMapData instance. The resulting cell indices are returned via the output parameters keyIndex and valueIndex. The retrieved key/value cell indices can then be used for example with setCell. If you are only interested in a key or value index, you may pass 0 as valueIndex or keyIndex. The QCPColorMap always displays the data at equal key/value intervals, even if the key or value axis is set to a logarithmic scaling. If you want to use QCPColorMap with logarithmic axes, you shouldn't use the QCPColorMapData::coordToCell method as it uses a linear transformation to determine the cell index. cellToCoord, QCPAxis::coordToPixel
References QCPRange::lower, mKeyRange, mKeySize, mValueRange, mValueSize, QCPRange::upper.
void QCPColorMapData::cellToCoord(int keyIndex, int valueIndex, double *key, double *value) const
Transforms cell indices given by keyIndex and valueIndex to cell indices of this QCPColorMapData instance. The resulting coordinates are returned via the output parameters key and value. If you are only interested in a key or value coordinate, you may pass 0 as key or value. The QCPColorMap always displays the data at equal key/value intervals, even if the key or value axis is set to a logarithmic scaling. If you want to use QCPColorMap with logarithmic axes, you shouldn't use the QCPColorMapData::cellToCoord method as it uses a linear transformation to determine the cell index. coordToCell, QCPAxis::pixelToCoord
References QCPRange::lower, mKeyRange, mKeySize, mValueRange, mValueSize, QCPRange::upper.