QCPLayer
QCustomPlot* QCPLayer::mParentPlot
Referenced by ~QCPLayer.
QString QCPLayer::mName
int QCPLayer::mIndex
QList<QCPLayerable*> QCPLayer::mChildren
Referenced by addChild, removeChild, ~QCPLayer.
bool QCPLayer::mVisible
Referenced by setVisible.
friend class QCustomPlot
friend class QCPLayerable
QCPLayer::QCPLayer(QCustomPlot *parentPlot, const QString &layerName)
Creates a new QCPLayer instance. Normally you shouldn't directly instantiate layers, use QCustomPlot::addLayer instead. It is not checked that layerName is actually a unique layer name in parentPlot. This check is only performed by QCustomPlot::addLayer.
QCPLayer::~QCPLayer()
References QCustomPlot::currentLayer, mChildren, mParentPlot.
QCustomPlot* QCPLayer::parentPlot() const
Referenced by QCPLayerable::moveToLayer.
QString QCPLayer::name() const
Referenced by QCustomPlot::layer, QCPLayerable::moveToLayer.
int QCPLayer::index() const
Returns the index this layer has in the QCustomPlot. The index is the integer number by which this layer can be accessed via QCustomPlot::layer. Layers with higher indices will be drawn above layers with lower indices.
Referenced by QCustomPlot::addLayer, QCustomPlot::moveLayer, QCustomPlot::removeLayer.
QList< QCPLayerable * > QCPLayer::children() const
Returns a list of all layerables on this layer. The order corresponds to the rendering order: layerables with higher indices are drawn above layerables with lower indices.
Referenced by QCustomPlot::deselectAll, QCustomPlot::draw, QCustomPlot::mouseReleaseEvent, QCustomPlot::removeLayer.
bool QCPLayer::visible() const
Referenced by QCPLayerable::realVisibility, setVisible.
void QCPLayer::setVisible(bool visible)
Sets whether this layer is visible or not. If visible is set to false, all layerables on this layer will be invisible. This function doesn't change the visibility property of the layerables (QCPLayerable::setVisible), but the QCPLayerable::realVisibility of each layerable takes the visibility of the parent layer into account.
References mVisible, visible.
void QCPLayer::addChild(QCPLayerable *layerable, bool prepend)
References mChildren.
Referenced by QCPLayerable::moveToLayer.
void QCPLayer::removeChild(QCPLayerable *layerable)
References mChildren.
Referenced by QCPLayerable::moveToLayer, QCPLayerable::~QCPLayerable.