geometry.h
Direction
Acces
bool operator==(Point< T > a, Point< T > b)
Point equality.
T a b true false
References Point< T >::x, Point< T >::y.
Direction operator>>(Point< T > a, Point< T > b)
Direction to point.
T a b Direction
References DirectionUnnown, Down, Left, Right, Up, Point< T >::x, Point< T >::y.
Direction operator<<(Point< T > a, Point< T > b)
Inverse direction to point.
T a b Direction
Point<T> operator+(Point< T > a, Point< T > b)
Point add do point.
T a b Point<T>
References Point< T >::x, Point< T >::y.
Point<T> operator-(Point< T > a, Point< T > b)
Substract point from point.
T a b Point<T>
References Point< T >::x, Point< T >::y.
Point<T> operator/(Point< T > a, T dev)
Devide point by number.
T a dev Point<T>
References Point< T >::x, Point< T >::y.
Point<T> operator*(Point< T > a, T mul)
Multiply point by number.
T a mul Point<T>
References Point< T >::x, Point< T >::y.
Acces operator+(Acces a, Acces b)
Append acces.
a b Acces
References Allowed, Forbiden, Unnown.
Point<double> operator+(Point< T > i, Point< double > d)
Point double and int addition.
T i d Point<double>
References Point< T >::x, Point< T >::y.
T measureDistance(Point< T >a, Point< T >b)
Distance from point to point.
T T
References Point< T >::x, Point< T >::y.
Point<double> doublePoint(Point< int > p)
Point of double from point of int.
p Point<double>
References Point< T >::x, Point< T >::y.
Referenced by measureDistance, Mouse::Mouse.
double measureDistance(Point< double >a, Point< int >b)
Distance from double point to int point.
double
References doublePoint.
Referenced by Mouse::Call.
Position<int> roundPosition(Position< double > pos)
Point<int> from Point<double>
pos Position<int>
References Position< T >::direction, Position< T >::localization, Point< T >::x, Point< T >::y.
Referenced by Mouse::Call.
Point<double> operator+(Point< double > a, Point< double > b)
Point<double> addition.
a b Point<double>
References Point< T >::x, Point< T >::y.
Direction RotateDirectionLeft(Direction d)
Rotate direction to left.
d Direction
References DirectionUnnown, Down, Left, Right, Up.
Referenced by Mouse::Call, Expander::Logic.
Direction RotateDirectionRight(Direction d)
Rotate direction to right.
d Direction
References DirectionUnnown, Down, Left, Right, Up.
Referenced by Mouse::Call, Expander::Logic, TurnAroundDirection.
Direction TurnAroundDirection(Direction d)
Rotate direction of 180 degree.
d Direction
References RotateDirectionRight.
Referenced by Expander::Logic.
Direction DirectionFromInt(int x)
Get Direction form int representation.
x Direction
References Down, Left, Right, Up.
Referenced by Expander::Logic, Expander::NearestPath, Expander::NearestPathToUnnown.