geometry.cpp
Acces operator+(Acces a, Acces b)
Append acces.
a b Acces
References Allowed, Forbiden, Unnown.
double measureDistance(Point< double >a, Point< int >b)
Distance from double point to int point.
double
References doublePoint.
Referenced by Mouse::Call.
Position<int> roundPosition(Position< double > pos)
Point<int> from Point<double>
pos Position<int>
References Position< T >::direction, Position< T >::localization, Point< T >::x, Point< T >::y.
Referenced by Mouse::Call.
Point<double> operator+(Point< double > a, Point< double > b)
Point<double> addition.
a b Point<double>
References Point< T >::x, Point< T >::y.
Point<double> doublePoint(Point< int > p)
Point of double from point of int.
p Point<double>
References Point< T >::x, Point< T >::y.
Referenced by measureDistance, Mouse::Mouse.
Direction RotateDirectionLeft(Direction d)
Rotate direction to left.
d Direction
References DirectionUnnown, Down, Left, Right, Up.
Referenced by Mouse::Call, Expander::Logic.
Direction RotateDirectionRight(Direction d)
Rotate direction to right.
d Direction
References DirectionUnnown, Down, Left, Right, Up.
Referenced by Mouse::Call, Expander::Logic, TurnAroundDirection.
Direction TurnAroundDirection(Direction d)
Rotate direction of 180 degree.
d Direction
References RotateDirectionRight.
Referenced by Expander::Logic.
Direction DirectionFromInt(int x)
Get Direction form int representation.
x Direction
References Down, Left, Right, Up.
Referenced by Expander::Logic, Expander::NearestPath, Expander::NearestPathToUnnown.